### ISSUE TITLE
CUDA toolkit 9 update reuqest. 

### ISSUE THREAD

**Issue by fuchanghao** [lltcggie/waifu2x-caffe#106]
It's already stable for a while.

**Comment by Heiseikiseki** [comment]
CUDA toolkit 9.1 is out.

**Comment by 2ji3150** [comment]
Cuda 10 and Cudnn 7.3 have been released. Hope there is a chancne for the update.

**Comment by lltcggie** [comment]
ver 1.1.9でCUDA Toolkitを10.0.130に、cuDNNをv7.3.1に更新しました。
