### ISSUE TITLE
Would you like to make a waifu4x based on SRGAN?

### ISSUE THREAD

**Issue by tuxzz** [lltcggie/waifu2x-caffe#110]
I found that SRGAN is very amazing on photo and anime-illust.
But there is no any product implemention based on it.  

I couldn't find any pretrained model.
I want to train this model on my own but my GPU is sucks.  

Would you like to make a waifu4x based on SRGAN?
I think it would be more better than waifu2x(SRCNN).

**TensorLayer Version(SRGAN-VGG19): https://github.com/tensorlayer/SRGAN**
**Some examples from: https://github.com/tensorlayer/SRGAN/issues/3**

Low resolution Image
--------------------
![image](https://user-images.githubusercontent.com/5357765/34611936-9c2581e2-f262-11e7-9acc-6de0bc193817.png)

Original High resolution Image
--------------------
![image](https://user-images.githubusercontent.com/5357765/34611939-a0ae366e-f262-11e7-9529-04acacfc23d1.png)

SRGAN Super resolution Image
--------------------
![image](https://user-images.githubusercontent.com/5357765/34611944-a39f9016-f262-11e7-9688-5cd0c309d630.png)

**Comment by CharonM72** [comment]
This is awesome! Seconded, if it's feasible.
すごい！可能あるなら僕も見たいです。

**Comment by YukiSakuma** [comment]
Yes it looks good, you should tried also asking @nagadomi

**Comment by tuxzz** [comment]
@YukiSakuma @nagadomi 's waifu2x is for web-service, it can't afford such a large model.

**Comment by lltcggie** [comment]
このソフトは他の方が作成したモデルを手軽に使えるようにするという趣旨なので、今のところ自分でモデルを学習させて追加する予定はないです。
