### ISSUE TITLE
waifu2x caffe ver 1.1.8.4 A fatal error has occurred. There is a possibility the split size is too large.

### ISSUE THREAD

**Issue by YukiSakuma** [lltcggie/waifu2x-caffe#111]
And then waifu2x-caffe crashes, Using cudnn64_7.dll library
Previous version doesn't have this error and crash

error output log shows only this

`cudnn_conv_layer.cpp:54] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR`

GPU driver 388.71

**Comment by ky0ncheng** [comment]
Use cudnn-9.2-windows10-x64-v7.1(cudnn64_7.dll), this error already-exists.

**Comment by mattreecebentley** [comment]
What do you mean?

**Comment by abearwithagun** [comment]
Fixed it. Better late than never, right? Until the pull request is merged, you can work around it by using a metadata editor to edit cudnn64_7.dll so that both the "File version" and "Product version" in the Details tab of the Properties menu start with a 6.

**Comment by lltcggie** [comment]
cuDNNの動作チェックでバージョンが古くても通していたのが問題だったので、v7.3未満はエラーになるようにしました。
