### ISSUE TITLE
Need Help for Build 

### ISSUE THREAD

**Issue by Heiseikiseki** [lltcggie/waifu2x-caffe#112]
I tried to build waifu2x-caffe with vs2017 but it failed.

fatal error C1083: include ファイルを開けません。'boost/shared_ptr.hpp':No such file or directory

ビルドの手順について教えて頂けないでしょうか。

**Comment by nagadomi** [comment]
Here are a few steps I did.

### caffe-builder
```
git clone https://github.com/lltcggie/caffe-builder.git
cd caffe-builder
```
Fix the download URL of HDF5 in `cmake/packages/HDF5.cmake`.
-> https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.zip
Put cudnn header/library files to `cudnn` directory.
Then follow the gist to build caffe. : https://gist.github.com/lltcggie/6af687bca94aba8c78b4

### waifu2x-caffe
```
git clone https://github.com/lltcggie/waifu2x-caffe.git
git submodule update --init --recursive
```
Edit VS PATH settings of caffe-builder and OpenCV according to your environment, and build.
