### ISSUE TITLE
Add resnet 10 model

### ISSUE THREAD

**Issue by Yolkis** [lltcggie/waifu2x-caffe#113]
model here https://github.com/tsurumeso/waifu2x-chainer/tree/master/models/resnet10

command waifu2x-chainer: python waifu2x.py -a 2 --tta --tta_level 8 -m noise -n 3 -i C:\input.jpg
setting waifu2x-caffe: Photography, Anime model; tta; denoice only level 3

original file
![original](https://user-images.githubusercontent.com/30495707/36305617-861a83e6-133e-11e8-88ce-91137203b88c.png)

waifu2x-caffe Photography, Anime model; tta; denoice only level 3
![waifu2x-caffe](https://user-images.githubusercontent.com/30495707/36305627-92f1d6d2-133e-11e8-9442-98d9f079ed06.png)

waifu2x-chainer resnet 10 model, tta level 8, denoice 3
![waifu2x-chainer](https://user-images.githubusercontent.com/30495707/36305651-a317ca6c-133e-11e8-881d-61fd350ced3b.png)

so i think resnet 10 model better for denoising, should add this model to this programm

**Comment by Yolkis** [comment]
comparison of 2d rgb model with waifu2x-chainer resnet 10 model in max tta mode and max denoice level

2d rgb model
![2d](https://user-images.githubusercontent.com/30495707/36338163-275f1b0c-13d2-11e8-8358-4ec6cd95befe.png)

waifu2x-chainer's resnet 10
![chainer](https://user-images.githubusercontent.com/30495707/36338164-2f3ce32c-13d2-11e8-8774-b06978fc2d44.png)

**Comment by Heiseikiseki** [comment]
Maybe you should Open this issue in https://github.com/nagadomi/waifu2x
That is the true waifu2x developer. And here is just the windows specific offline version.

**Comment by lltcggie** [comment]
upresnet10を取り込んだので、resnet10を取り込む予定はありません。
