### ISSUE TITLE
Error image output with very rare probability

### ISSUE THREAD

**Issue by chungexcy** [lltcggie/waifu2x-caffe#12]
There is a very small probability that you will find that your output image (like .png) might be broken. This happened on my machine and my friend's machine.

The broken image has the corrected file size (this might indicate the calculation process is corrected). The first part of image (basically the top lines of a image) is showing correctly, and the rest of it is broken (like displaying black area or error texture).

The probability is very low, like several errors in 100,000 example. But I found they are more likely to occur within a small period of time, or even continues images.

**Comment by lltcggie** [comment]
特定の画像で壊れるわけでは無いのですね？
処理前の画像と壊れた画像、変換の設定、実行した時の環境（OSやGPUなど）を教えていただけますか？

**Comment by chungexcy** [comment]
No, the error occurs randomly, If you do it again on those images, you will get the corrected answers with the same size. So the source is corrected and no error shows up during the calculation.

About the conversion, it seems to be occurred on any modes, at least I find scaling and denoising is affected. The my OS is windows 7 64 bit with GTX 960 cuddn, and my friend uses windows 8.1 64 bit with GTX 980ti cuddn. I don't believe the cnn inference calculation is wrong.

**Comment by lltcggie** [comment]
こちらの環境はOS: Windows 8.1 x64, GPU: GTX 660でcuDNNを使っているのですが、出力結果が壊れた画像になったことは一度もないですね…
cuDNNでなくCUDAを使っても壊れますか？

**Comment by chungexcy** [comment]
I'm still not so sure that this is indeed caused by the program. But I did find this possible bug. You can try processing a large sequence of image that is extracted from a video. And hopefully, this error will reappear 10 times in 100,000 tests.
I never run lots of image with CUDA. So I didn't know whether CUDA would lead this error or not.

**Comment by lltcggie** [comment]
GUIで大量の画像を変換すればいいんですね？
今度長時間パソコンに触らない時間ができたら試してみます（いつになるかはわかりませんが）

**Comment by gbaoye** [comment]
3000ピクセル以上の画像

.WEBP形式に出力することはできません

**Comment by lltcggie** [comment]
@gbaoye ここで議論されている問題とは別の問題なので、新しくIssueを立ててください。
また、再現方法がわからなかったので
・入力画像の縦幅、横幅、フォーマット
・変換処理の内容
・出力形式の具体的な設定
・「WEBP形式に出力することはできません」とは具体的にどういうことなのか？（例えば正常に終了したはずなのに画像が出力されないなど）
などの情報を書いてください。

**Comment by gbaoye** [comment]
出力画像を「D:\1\测试\0000a(RGB)(auto_scale)(Level2)(x2.000000).webp」に書き込めませんでした
テスト画像は3745X1600です
PNGは、問題ありません
おそらく唯一のゴージャス3000x3000上の写真で

2016-03-06 22:50 GMT+08:00 lltcggie <notifications@github.com>:

**Comment by Heiseikiseki** [comment]
@gbaoye 
(gbaoyeは中国人らしいのでついでに中国語訳)

WebPの幅と高さには最大16383ピクセルに制限されてる､これは仕様です｡
（WebP的长宽其中一边必不能超过16383像素，这是规格上的限制）

ここで議論されている問題とは別の問題なので、新しくIssueを立ててください。
ー>这个议题已经和本议题脱离关系，若要讨论请再建立一个issue

**Comment by gbaoye** [comment]
Qはどうもありがとうございました
グッド説明
WEBPしかし、それはそうは変換システムのACDSeeの制限はありません

2016-03-07 7:53 GMT+08:00 Heiseikiseki <notifications@github.com>:

**Comment by lltcggie** [comment]
こちらで大量の画像変換を試してみたところ、VRAMの使用量が最大ギリギリだとおかしなデータが出力されることがあるようです。
crop_sizeを減らすと安定して変換することが出来ます。

この動作は仕様とするのでIssuesを閉じます。
