### ISSUE TITLE
Cudnn64_7.dll not found error

### ISSUE THREAD

**Issue by Nonymous1** [lltcggie/waifu2x-caffe#120]
So I installed Cuda v10, followed these steps:
docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-windows
and still get this error. GPU is latest driver GTX 1060 3GB 
What is wrong?

**Comment by usagicore** [comment]
cuDNN for CUDA 10 is not compatible. Use CUDA 9 instead.

**Comment by Nonymous1** [comment]
Nevermind a reboot fixed it, CUDA 10 works.
