### ISSUE TITLE
Port to HIP-caffe

### ISSUE THREAD

**Issue by forcegeckoness** [lltcggie/waifu2x-caffe#122]
As I don't have the knowledge to do this, I kindly ask:
Would it be possible and not very time-consuming compile it with HIP?
With such tool many AMD users would be able to also use our graphics cards.

https://gpuopen.com/ported-caffe-hip-heres-happened/

https://github.com/ROCmSoftwarePlatform/hipCaffe

Thank you for your attention.

**Comment by lltcggie** [comment]
流石にこちらがCaffeに加えている変更の移植コスト、ADM環境を用意するコスト、移植後の検証コストなどが高すぎるので対応予定はありません。
