### ISSUE TITLE
特定の環境でCUnetモデルを使用するとクラッシュする

### ISSUE THREAD

**Issue by f11894** [lltcggie/waifu2x-caffe#133]
CUnetモデルをCPUで使用するとGUI、CUI問わずクラッシュしてしまいます
分割サイズやバッチサイズを変えても変化はありませんでした
UpResNet10モデルは使えます

waifu2x-caffe ver 1.2.0
Windows 10 64bit Version 10.0.17763.134
CPU Ryzen 2400G
外部GPU無し
RAM 8GB

追記ですが分割サイズは64や128などの4の倍数にしてもクラッシュしました

**Comment by 2ji3150** [comment]
変ですね。こちらはどちらも動きました。

waifu2x-caffe ver 1.2.0
Windows 10 64-bit Version 10.0.17763.134
CPU: i7-8700k
GPU: GTX 1060 6G
RAM:16GB

**Comment by nagadomi** [comment]
ここにPoolingの条件がないので、cuDNNがある環境でCPUが使えないのだと思います。
https://github.com/lltcggie/waifu2x-caffe/blob/e5c310f851e3fdbd3a95431da468e326df22ca38/common/cNet.cpp#L394-L426

```
         } else if (type == "Pooling")
         {
             if (process == "cudnn")
                 layer_param->mutable_pooling_param()->set_engine(caffe::PoolingParameter_Engine_CUDNN);
             else
                 layer_param->mutable_pooling_param()->set_engine(caffe::PoolingParameter_Engine_CAFFE);
         }
```
UpResNet10はprototxtのpooling_paramに`engine: CAFFE`が入っているのでcuDNNを使おうとせず問題が出ていないのだと思います。

**Comment by f11894** [comment]
まさにそのとおりのようでした。
prototxtに「engine: CAFFE」を追記したところ正常に変換出来ました。
