### ISSUE TITLE
LANCZOS

### ISSUE THREAD

**Issue by 2ji3150** [lltcggie/waifu2x-caffe#136]
私の理解が間違ってなければ、
「scale_width」「scale_height」と「scale_ratio」
は 必要な十分にカバーするように、2倍拡大を繰り返し行って 最後に**線形フィルタ**で縮小します

出力の画質をアップするため、
waifu2x-caffeの内部の処理が出力画像の画質に関わりがある部分をcv::INTER_LANCZOS4が使えるようにしてほしい。

度々申し訳ございません。
よろしくお願いいたします。

**Comment by lltcggie** [comment]
縮小は線形フィルタではなく縮小率が0.5以上の場合は`cv::INTER_CUBIC`、0.5未満の場合は`cv::INTER_AREA`を使用するようにしているので、現在の処理で十分だと思います。
https://github.com/lltcggie/waifu2x-caffe/blob/c131ca38c48b05947d69f9bfc49ec4c60ba0ed4b/common/stImage.cpp#L745-L760

**Comment by 2ji3150** [comment]
なるほど。となるとReadmeにある

> 2の累乗以外の数値が指定されている場合は、指定倍率になるように拡大した画像を線形フィルタで縮小します。

は修正するべき情報なんでしょうか

**Comment by lltcggie** [comment]
以前この実装に変更したときにその記述を直すのを忘れたので修正しました。 2608a2e85c9fc247ea5c468fd1e49deba0e25c06
ご指摘ありがとうございます。
