### ISSUE TITLE
Unable to use UpResNet10 model on GPU

### ISSUE THREAD

**Issue by NeoISE** [lltcggie/waifu2x-caffe#138]
My system is i7-4700MQ CPU and a GT 740M GPU and using waifu2x-caffe version 1.1.9.2 and have the CUDA option selected in settings.
When I use any RGB models, I can see in Win10 Task Manager that the GPU is being used; holding usage at around 100 percent (just as expected) with some usage increase in CPU.
When UpResNet10 model is selected, it only reports that the CPU is used and the GPU is showing no signs of usage besides an increase in GPU memory.

**Comment by HASJ** [comment]
I would guess that the GT 740M just can't compute the UpResNet10 model.
