### ISSUE TITLE
ノイズ除去と拡大でUpCUnetではなくCUnetが使われている可能性

### ISSUE THREAD

**Issue by f11894** [lltcggie/waifu2x-caffe#141]
本来はノイズ除去使用時はCUnetが、ノイズ除去と拡大使用時にはUpCUnetが選択されるのが正常な動作だと思うのですが現状ではそうなっていないような気がします。
私はソースコードが読めるわけでは無いのでwaifu2x-caffeを使用したときの挙動で推察しているだけなのですが根拠をいくつか書きます。

1 UpCUnetが使われているときはノイズ除去単体のモデルファイルがフォルダに無くても変換出来るはずなのに予め削除しておくと「モデルファイルが開けませんでした」というエラーが出て変換出来ない。
2 Up系のモデルは変換モードが拡大のみの場合とノイズ除去と拡大で同じくらいの変換時間になるはずなのにノイズ除去と拡大のほうが少し時間がかかっている。
3 info.jsonを開いて「"has_noise_only":true」の部分を消すと上記2つの症状が無くなる。

またCUnetでノイズ除去と拡大していると推察している動作の時の方がメモリの消費量が倍多いです。
ご多忙だとは思いますが動作の確認をしていただけないでしょうか？

**Comment by 2ji3150** [comment]
has_noise_only":trueは間違って入れたのかもしれませんね。そのフラグがある限りnoisescaleは動作しない模様です。
