### ISSUE TITLE
Is it possible to train the project with my own images?

### ISSUE THREAD

**Issue by RuikangSun** [lltcggie/waifu2x-caffe#143]
I want to train the project with some images, is it possible?

**Comment by Yolkis** [comment]
> I want to train the project with some images, is it possible?

https://github.com/nagadomi/waifu2x/tree/dev

**Comment by lltcggie** [comment]
Caffeのモデルを使用しているので同梱されているprototxtを使ってCaffeで学習させることは可能ですが、Yolkisさんに書いていただいた通り本家waifu2xの学習機能を使う方が簡単だと思います。
