### ISSUE TITLE
Failed to tranfrom in all mode

### ISSUE THREAD

**Issue by 1349422030** [lltcggie/waifu2x-caffe#147]
Just remind this
![default](https://user-images.githubusercontent.com/35253997/52134464-9344b880-267e-11e9-8d4a-f92cad5be76c.png)
In English, these words probably be 
"There was a fatal mistake. Separation size may be too large"
In Japanese, these words probably be 
"致命的なミスが起こった。分割サイズが大きいかもしれない"

**Comment by hh1217130737** [comment]
看软件界面我想我用中文回答就OK了
检查是否有安装CUDA和cuDNN，如果没有就安装一下下，如果有安装的话就看一下版本，最新版的waifu2x要求官网下载的最新的驱动（目前为止最新的），安装后就可以用了。因为这个软件就是基于这个的，不安装可能就会出各种问题。
我一开始也是老版本用得好好的，新版本安装上就也是拆分尺寸过大，无法使用cuDNN，然后更新了就能用了，还有问题请追问

**Comment by LinLingxin** [comment]
恩，因为毕竟不是作者，源码我也没完全看，所以就说一下我个人的理解吧。caffe版为N卡版这个你应该知道，所以他的处理就如设置中所说的，走CUDA（也就是走NVIDIA显卡，如支持cuDNN则使用cuDNN）或者CPU。而当你安装了相应的驱动程序之后自然而然的也就可以使用了。在设置中优先使用CUDA，这使得GPU设置默认也就是走N卡了，但当强制设置为1的时候，个人认为会强制从N卡转向你的集显，这时由于集显并不支持CUDA，自然而然也就出现了这个问题。我想作者这么设计应该是考虑到双独显的情况而设置的。个人理解哈。

**Comment by Rhapsodyx2** [comment]
> 看软件界面我想我用中文回答就OK了
> 检查是否有安装CUDA和cuDNN，如果没有就安装一下下，如果有安装的话就看一下版本，最新版的waifu2x要求官网下载的最新的驱动（目前为止最新的），安装后就可以用了。因为这个软件就是基于这个的，不安装可能就会出各种问题。
> 我一开始也是老版本用得好好的，新版本安装上就也是拆分尺寸过大，无法使用cuDNN，然后更新了就能用了，还有问题请追问

您好，想请教一下，我安装了CUDA tool kit 10.0, 把cuDNN v7.3.1放在了waifu2x cafee的根目录, 但是我用CUDA模式还是报错，遇到的是和楼主一样的报错信息，可能是什么原因呢？我的显卡是980M，系统是windows 8.1. 非常感谢。

**Comment by 1349422030** [comment]
> 
> 
> > 看软件界面我想我用中文回答就OK了
> > 检查是否有安装CUDA和cuDNN，如果没有就安装一下下，如果有安装的话就看一下版本，最新版的waifu2x要求官网下载的最新的驱动（目前为止最新的），安装后就可以用了。因为这个软件就是基于这个的，不安装可能就会出各种问题。
> > 我一开始也是老版本用得好好的，新版本安装上就也是拆分尺寸过大，无法使用cuDNN，然后更新了就能用了，还有问题请追问
> 
> 您好，想请教一下，我安装了CUDA tool kit 10.0, 把cuDNN v7.3.1放在了waifu2x cafee的根目录, waifu2x cafee是最新版的，老版本的也试过，只要我用CUDA模式会报错，遇到的是和楼主一样的报错信息，可能是什么原因呢？我的显卡是980M，系统是windows 8.1. 非常感谢。

目前我的解决办法是，升级nvidia驱动，去官网下载然后升级那种，不使用第三方软件更新。然后前面提到的使用GPU的No.就填写0。目前我能够正常运行了

**Comment by byteslaves** [comment]
> > > 看软件界面我想我用中文回答就OK了
> > > 检查是否有安装CUDA和cuDNN，如果没有就安装一下下，如果有安装的话就看一下版本，最新版的waifu2x要求官网下载的最新的驱动（目前为止最新的），安装后就可以用了。因为这个软件就是基于这个的，不安装可能就会出各种问题。
> > > 我一开始也是老版本用得好好的，新版本安装上就也是拆分尺寸过大，无法使用cuDNN，然后更新了就能用了，还有问题请追问
> > 
> > 
> > 您好，想请教一下，我安装了CUDA tool kit 10.0, 把cuDNN v7.3.1放在了waifu2x cafee的根目录, waifu2x cafee是最新版的，老版本的也试过，只要我用CUDA模式会报错，遇到的是和楼主一样的报错信息，可能是什么原因呢？我的显卡是980M，系统是windows 8.1. 非常感谢。
> 
> 目前我的解决办法是，升级nvidia驱动，去官网下载然后升级那种，不使用第三方软件更新。然后前面提到的使用GPU的No.就填写0。目前我能够正常运行了


试了，最新版的驱动还是拆分过大问题，win10，gtx950m，445.75版驱动，更新于2020.3月，cuda和cudnn都安装并能检查可用。

**Comment by shikkoku** [comment]
拆分过大问题我就遇到
https://github.com/lltcggie/waifu2x-caffe/issues/147#issuecomment-459946350
的特定情况了……旧有设置是GPU1，但新系统GPU0才是独立显卡（我是台式电脑）。

**Comment by userElaina** [comment]
你好，我也遇到了同样的问题……cuda和cudnn都安装完毕可用，仍然报错拆分尺寸过大。是不是因为我的硬件配置过低？（显存128MB的轻薄本）
