### ISSUE TITLE
Half CPU usage

### ISSUE THREAD

**Issue by ffleader1** [lltcggie/waifu2x-caffe#15]
I'm not sure if this is an issue or not, but a guy introduced me this program and it works really great. However, the program only uses half of my CPU, an I7 4770k. He told me that the program constantly uses 100% of his CPU (i5-3570K). So, problem with Hyper Threading? I don't know, just submit the problem here.
![50 cpu](https://cloud.githubusercontent.com/assets/15016720/13083961/daf4a466-d509-11e5-88ce-0216dd657c51.png)

**Comment by lltcggie** [comment]
CPUの使用率が約50%に見えるのは表示だけで、実際の使用率は約100%近くだと思います。

CaffeやOpenBLASの内部を詳しく見たわけではないので推測ですが、計算の並列化は論理コア数ではなく物理コア数に対応するように行っていると思われます。（Hyper Threadingを有効にすると計算速度が遅くなるらしいので）
Core i7-4770Kは物理コア数4、 論理コア数8なので、プログラム実行時に「リソース　モニター」で各CPUの使用率を見ると、4つのCPUの使用率が約100%、残り4つのCPUの使用率が約0%になっていると思います。(プログラムのCPU使用率はこれらの平均の約50%と表示される)

**Comment by ffleader1** [comment]
I think Task Manager read the CPU usage correctly. When running 1x Waifu x2, I was able to do various task easily, and the fan is not loud, due to 50% CPU not being used. Also, I was able to get CPU usage to 75% by running 2x Waifu x2 at the same time. :smile: Anyway, nice program. Much better in upscaling than Photoshop. :+1:
![75 1](https://cloud.githubusercontent.com/assets/15016720/13097670/bbbe0a00-d555-11e5-8503-ed526e4415e1.png)
![75 2](https://cloud.githubusercontent.com/assets/15016720/13097671/bbe61aa4-d555-11e5-8b71-56e2432e1a3b.png)

**Comment by lltcggie** [comment]
すいません、CPUを使い切れていないのはCaffeの仕様か、僕の使い方が悪いせいのようですね…
現状では仕様ということにしておいてください。

**Comment by ffleader1** [comment]
Ok. I will provide an update if I can buy an i7 6900k (not even out yet) later :D

**Comment by Jadelor** [comment]
@ffleader1 it's a hyperthreading quirk. The CPU of your friend doesn't support hyperthreading at all (I checked the specs) so the Windows task manager shows all of his 4 CPU cores in use (100%). On your hyperthreading-capable CPU, however, it doesn't differentiate between the 4 cores and the 4 ht extensions (8 in total), so it looks like you're only using 50­%.

**Comment by ffleader1** [comment]
Ok. After using the program for a while, I have some feedback.
1) The %CPU use for **Hyper Threading **depends on the number of Window of Waifu x2.
- 1 Wifefu x2 Running: 50% CPU usage
- 2 Wifefu X2 Running at the same time: 75% CPU usage (37.5% each)
- 3 Wifefu X2 Running at the same tine:  87.5% CPU usage (29.2% each)
So I guess there is a formula to this. Check below.
2) The program works well with common resolution image like 480p, 720p, 1080p; however, for big images, it doesn't work really well. Denoise still leaves atrifact and Magnify is not very sharp, compared to upscaling from lower resolution,
![image](https://cloud.githubusercontent.com/assets/15016720/13291862/0d7a4d76-db4c-11e5-9222-24a5165fb309.png)

**Comment by YukiSakuma** [comment]
^Looks good I might try your method of upscaling then downscaling and then upscaling again to look better but you said that the sharpness decreases as you upscale so what I do is go increase the (upscaled image) sharpness in Photoshop
