### ISSUE TITLE
Which command line model corrosponds to which GUI model?

### ISSUE THREAD

**Issue by JouMxyzptlk** [lltcggie/waifu2x-caffe#156]
Command line model models\upconv_7_anime_style_art_rgb gives me the best result for my current batch.
But which GUI-Model is upconv_7_anime_style_art_rgb? I tried them all seven of them and the result looked different.
I also notice I have eight models on the cmdline version, so that exact model might be missing in the GUI version...
Apart from that: Running very stable and very well here, > 200'000 frames already upsampled...

**Comment by nagadomi** [comment]
| model_dir | Resource ID | English Label |
|---------------|------------------|--------------------|
|models/upconv_7_anime_style_art_rgb|IDC_RADIO_MODEL_UPCONV_RGB|2-D illust (UpRGB Model)
|models/upconv_7_photo|IDC_RADIO_MODEL_UPCONV_PHOTO|Photo (UpPhoto Model)
|models/anime_style_art_rgb|IDC_RADIO_MODEL_RGB|2-D illust (RGB Model)
|models/photo|IDC_RADIO_MODEL_PHOTO|Photography, Anime
|models/anime_style_art|IDC_RADIO_MODEL_Y|2-D illust (Y Model)
|models/upresnet10|IDC_RADIO_MODEL_UpResNet10|2-D illust (UpResNet10)
|models/cunet|IDC_RADIO_MODEL_CUNET|2-D illust (CUnet Model)

From code.
https://github.com/lltcggie/waifu2x-caffe/blob/8b53d0f086f44723cb6e101c12e42e63fb4c6a63/waifu2x-caffe-gui/MainDialog.h#L39-L69
https://github.com/lltcggie/waifu2x-caffe/blob/master/bin/lang/english.json

model/ukbench is  prototype of  photo model made long time ago, just ignore it.

**Comment by JouMxyzptlk** [comment]
Thank you!
