### ISSUE TITLE
How to start GUI directly

### ISSUE THREAD

**Issue by bananakid** [lltcggie/waifu2x-caffe#16]
You just drag'n'drop waifu2x-caffe.exe to Command Prompt and hit Enter.
You can create a shortcut: right-click any Windows Explorer window, select New, select Shortcut and input this target
`C:\Windows\System32\cmd.exe /c "C:\Program Files\waifu2x-caffe\waifu2x-caffe.exe"`
You may need to edit path depending on the location of waifu2x-caffe.exe

**Comment by YukiSakuma** [comment]
What is input batch size? and if so can you provide a tutorial how to use VapourSynth waifu2x filter I am having a hard time on the instructions on how to install it..

**Comment by lltcggie** [comment]
@bananakid こちらではコマンドプロンプトからwaifu2x-caffe.exeを起動してもエラーが発生しませんでした。エラーメッセージを書いていただけると解決に繋がるかもしれません。

**Comment by lltcggie** [comment]
@ YukiSakuma 「batch size」はREADMEの「--batch_size」の項に説明が書いてあります。そこに書いてあるように分割サイズ(crop_size)を指定できればbatch sizeは必要ないので、GUIにはbatch sizeの入力欄を入れていません。VapourSynthは僕は使っていないのでよくわかりません。
