### ISSUE TITLE
最新版用の韓国語ファイルです。

### ISSUE THREAD

**Issue by aruhirin** [lltcggie/waifu2x-caffe#165]
３年ぶりですね。
このような素晴らしいプログラムを
作って頂き、ありがとうございます。
いつも感謝しております。

久しぶりに使ってみながら
前に翻訳したところを改善し、
追加された項目にも対応いたしました。

ver 1.2.0.2用の韓国語ファイルを
添付いたしますで反映して頂けると
ありがたいです。
[korean.zip](https://github.com/lltcggie/waifu2x-caffe/files/3048840/korean.zip)

**Comment by lltcggie** [comment]
ありがとうございます。
新しいバージョンで反映させていただきます。
