### ISSUE TITLE
There is a problem with tiff and webp conversion in the CUI program. (Image files are image files in yuv420p pixel format extracted with ffmpeg.)

### ISSUE THREAD

**Issue by gample** [lltcggie/waifu2x-caffe#172]
I tried to convert a tiff using the yuv420 pixel format for testing, but an error occurred.
However, the waifu2x-caffe GUI program completes the conversion without error.

Also, for webp, it displays a Japanese langauge to message that the conversion is complete, but no conversion is done.
 
The CUI program does not seem to be compatible with tiff and webp image formats.

In waifu2x-converter-cpp, the operation worked fine.
I would like to do the same thing with TTA and cudnn, but the error occurred and there was a problem with the conversion.

Is this a problem with the command? Or is it a problem with the CUI program?

The command is as follows:
D:\\Utility\\video2x\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe --output_extention tiff --mode noise_scale --scale_ratio 2.0 --noise_level 0 --process cudnn --crop_size 1024 --output_quality -1 --output_depth 8 --batch_size 1 --input_path D:\\Utility\\video2x\\1 --output_path D:\\Utility\\video2x\\2

**Comment by nagadomi** [comment]
Regarding webp, you need to add the `-l webp` option. The default value of `input_extention_list`(-l) is "png: jpg: jpeg: tif: tiff: bmp: tga",  it seems that webp is not contained, so `*.webp` is skipped.

**Comment by gample** [comment]
What should I do with a tiff file?

**Comment by gample** [comment]
Ented "png: jpg: jpeg: tif: tiff: bmp: tga" in input_extention_list.
but "tiff" file too, it displays a Japanese language to message that the conversion is complete, but no conversion is done.

**Comment by gample** [comment]
And nted "png:jpg:jpeg:tif:tiff:bmp:tga" in input_extention_list.
To "cudaSuccess (2 vs 0) out of memory" error.

**Comment by gample** [comment]
Oops, the cause of the error was excessive crop_size.
Fixed crop_size to 128.
