### ISSUE TITLE
Malfunction of split size auto-selection 分割サイズ自動設定に関する問題

### ISSUE THREAD

**Issue by glassonion0323** [lltcggie/waifu2x-caffe#175]
1. My environment:
Windows 7 SP1 64 bit
Intel i7-4770K
GeForce GTX 1060
GeForce Driver version 431.36
waifu2x-caffe ver 1.2.0.2
2. Set the GUI application as follows:
Conversion mode: Magnify only
Magnification Scale: 2.0
Model: CUnet model
Split size: 128
Batch size: 1
3. Drop a 250x250 or 500x500 pixel image to "Input path" textbox. Then split size is set to 125 automatically.
Example image:
![popup_miku](https://user-images.githubusercontent.com/14145757/61176210-c7da7a00-a5f7-11e9-98f2-a900a13509a0.jpg)
(This illustration of Hatsune Miku is licensed under CC BY-NC. https://piapro.net/intl/en_for_creators.html)
4. Perform conversion. Though the conversion finishes showing no error messages, the result seems to be corrupted.
Result of the image above:
![popup_miku(CUnet)(scale)(x2 000000)](https://user-images.githubusercontent.com/14145757/61176212-d0cb4b80-a5f7-11e9-812e-01c6f003042b.png)

I was able to convert the image normally by changing split size to 128 manually. Or by selecting another model and selecting CUnet again, split size became 128 and the image was converted normally. I noticed that 125 disappeared from the split size drop-down list after re-selecting CUnet model.

1. 環境
Windows 7 SP1 64 bit
Intel i7-4770K
GeForce GTX 1060
GeForce Driver version 431.36
waifu2x-caffe ver 1.2.0.2
2. GUI版を以下のように設定します
変換モード: 拡大
拡大率: 2.0
モデル: CUnet
分割サイズ: 128
バッチサイズ: 1
3. 250x250または500x500ピクセルの画像を「入力パス」にドロップします。すると分割サイズが自動で125に切り替わります。
（初音ミクの画像はCC BY-NCで、本家waifu2xのページでも使用されていますので例として使用させて頂きました。）
4. 変換を実行します。エラーメッセージ等は表示されずに完了しますが、変換結果は上の例のように破損しています。

分割サイズを128に設定することで正常に変換ができました。また、別のモデルを選択した後にCUnetを再度選択すると、分割サイズは128になり、正常に変換が行われました。CUnetを再選択した後に確認すると、分割サイズのドロップダウンリストの選択肢から125がなくなっていました。

**Comment by Cirnyan** [comment]
This seems to happen when both sides of the image are even multiples of 125, regardless of model, scaling or denoise settings.
I made an issue report of it earlier, but was just told it had been fixed, despite it clearly being a present problem.

**Comment by glassonion0323** [comment]
Same issue as https://github.com/lltcggie/waifu2x-caffe/issues/164
