### ISSUE TITLE
Arbitrary scaling problem

### ISSUE THREAD

**Issue by chrispolo** [lltcggie/waifu2x-caffe#185]
Hi, this is really a great job and helps me a lot, but I want to know if there is a corresponding version that can achieve arbitrary scaling, such as: 1.05, 1.1, 2.2 and so on;

**Comment by yoonhakcher** [comment]
You CAN use waifu2x-caffe to scale to any size.

**Comment by chrispolo** [comment]
@yoonhakcher Thank you,i will try it.
