### ISSUE TITLE
A fatal error has occurred. There is a possibility the split size is too large

### ISSUE THREAD

**Issue by Maelcat** [lltcggie/waifu2x-caffe#193]
![image](https://user-images.githubusercontent.com/53267697/80625245-8c882b00-8a12-11ea-91d3-3828b17b2b41.png)

**Comment by Maelcat** [comment]
[error_log_20200429-130440.txt](https://github.com/lltcggie/waifu2x-caffe/files/4553491/error_log_20200429-130440.txt)
original log was .14908

**Comment by nagadomi** [comment]
>(10 vs. 0)  invalid device ordinal

This error occurs when the GPU device(video card) is unavailable.
If your PC has multiple GPU devices, make sure `App Settings > GPU No` is correct NVIDIA GPU No (usually it is 0 or 1).

**Comment by Maelcat** [comment]
Ok, that was pretty confusing since my computer always refer as GPU 1 to NVIDIA GPU, but in the case of waifu2x it was GPU 0

**Comment by Maelcat** [comment]
Thanks!
