### ISSUE TITLE
cuDNN Not Found

### ISSUE THREAD

**Issue by aaronth07** [lltcggie/waifu2x-caffe#197]
I put `cudnn64_7.dll` into the `cudnn_data` folder, yet it still says it's not found.

**Comment by nagadomi** [comment]
cudnn.dll should be placed in the same folder as waifu2x-caffe.exe, not the cudnn_data folder.

**Comment by lltcggie** [comment]
ver 1.2.0.3で `cudnn64_7.dll` を同梱するようにしたので今後は問題ないと思います。
