### ISSUE TITLE
English please

### ISSUE THREAD

**Issue by FrankyBoy** [lltcggie/waifu2x-caffe#2]
because other people might want to work on it, too.

**Comment by NathanLovato** [comment]
There is an english repo, not sure if it's the exact same tool, but you do get the cuda-powered waifu2x algorithm: https://github.com/nagadomi/waifu2x

**Comment by lltcggie** [comment]
メッセージを英訳してくださった方がいるので、余裕ができたらやろうと思っています。
https://github.com/paul70078/waifu2x-caffe/commit/1ddc7d3903b3483e6d9366bb659651a22847a96b

**Comment by Phisherman** [comment]
@FrankyBoy Just found this
![waifu-caffee-illu-text](https://cloud.githubusercontent.com/assets/2873986/11766807/6ab1bc48-a197-11e5-875b-10889cd7b94d.png)

**Comment by MaverickTse** [comment]
↑That is the illustration I posted on videohelp.com for an early version of this software:
http://forum.videohelp.com/threads/372157-New-upscaling-algorithm-waifu2x

Translating the GUI directly is possible, but will be a maintenance nightmare unless all display strings are polled into a centralized place (e.g. String Resource, xml...)

**Comment by Phisherman** [comment]
@MaverickTse Thanks for clarification. The new version has some additional options. Could you please provide a new translation picture for that?

**Comment by MaverickTse** [comment]
![waifu2x-caffe-20151213-new_annotate](https://cloud.githubusercontent.com/assets/10569988/11766943/05e3e882-a1d7-11e5-8957-275de266a96e.png)

Here you are (for the new features only)

**Comment by Phisherman** [comment]
@MaverickTse I really appreciate it. Thanks!

**Comment by usagirei** [comment]
On the topic, the CLI version works wonders too, setup a batch file once and you're good. I put a few shortcuts with preset scales on the shell:sendto menu, then it's a matter of Right click > send to > batch processing. 

With the added bonus of in case of crash, you can select only the missing ones after since it won't stop them all.

I can put my scripts on a gist if there's interest.

**Comment by MaverickTse** [comment]
Quickly assembled up an easy-to-localize GUI for this:
https://github.com/MaverickTse/waifu2x_caffe_multilang_gui/releases/tag/1.0.0

see if it crash on your machine :-)

**Comment by Airbus480** [comment]
@MaverickTse In the newer versions of waifu2x-caffe there is a parameter added called TTA  or test time augmentation (I need a clear and simple definition of TTA). I tested it, it seems TTA makes the image more smoother than without using TTA however it takes longer time and I just tested a 900x1200 image and I tried to upscale x9 with TTA however waifu2x-caffe crashed (ver.1.0.8.1 using cuDNN). Without TTA it can upscale the image (900x1200) to 8100*10800

**Comment by MaverickTse** [comment]
Translated from the readme:
TTA: Increase PSNR by around 0.15 but 8 times slower

**Comment by Airbus480** [comment]
Update I was finally able to upscale with TTA without crashing by lowering the block size to 64 (before it was in the hundreds) but oh boy it reached a peak working set of 13.9 Million K with a peak commit size of 30 Million K. It took a full 37 minutes to complete it.

**Comment by lltcggie** [comment]
GUI now supports English ver 1.1.0.
何か翻訳に問題があったらIssuesでお知らせください。
