### ISSUE TITLE
READMEとver 1.1.2.1の韓国語訳、その外

### ISSUE THREAD

**Issue by aruhirin** [lltcggie/waifu2x-caffe#20]
使い方を習うため、READMEを読ませていただきました。
日本語の勉強も兼ねて翻訳しました。これは使わなくても大丈夫です。
[README for Korean.txt](https://github.com/lltcggie/waifu2x-caffe/files/182496/README.for.Korean.txt)
ところで、おかしなところがいくつかありました。
まず、「拡大サイズ」のところなんですが、
 * 変換後の縦幅で指定 : 画像の縦横比を維持したまま、指定された横幅になるように拡大します(単位はピクセル)
になっております。「縦幅になるように拡大します。」ではないでしょうか？
それと、`その他`の説明が`処理速度設定`の説明と同じです。
最後に、CUI版の使い方に
-s <小数点付き数値>, --scale_ratio <小数点付き数値>・・・のところは既に修正なさいましたね。（汗）

README.txtのエンコーディングがANSIになっておりますが、OSの言語設定によっては文字がまともに出ない場合があります。特にANSIにする理由がなければUTF-8をお勧めします。

そして、ver 1.1.2.1の韓国語訳です。
[korean.zip](https://github.com/lltcggie/waifu2x-caffe/files/182535/korean.zip)

それと、出力拡張子がjpgの時、出力画質設定の値を指定しても保存されず、次の起動の時はまた95に固定されているんですが、これは変えられないんですか？

**Comment by lizardon1995** [comment]
can add Chinese_Traditional language?
`{
"IDC_STATIC_IO_SETTING":"輸入和輸出設置",
"IDC_STATIC_INPUT_PATH":"輸入路徑\r\n(可使用文件夾)",
"IDC_BUTTON_INPUT_REF":"瀏覽文件",
"IDC_STATIC_OUTPUT_PATH":"輸出路徑",
"IDC_STATIC_TANS_EXT_LIST":"在文件夾中轉換的擴展名",
"IDC_STATIC_OUTPUT_EXT":"輸出擴展名",
"IDC_STATIC_OUTPUT_QUALITY":"輸出質量設置",
"IDC_STATIC_OUTPUT_DEPTH":"輸出位深度",
"IDC_STATIC_AUTO_START":"自動開始設定",
"IDC_RADIO_AUTO_START_NONE":"不自動開始",
"IDC_RADIO_AUTO_START_ONE":"輸入文件",
"IDC_RADIO_AUTO_START_MULTI":"輸入多個文件或文件夾",
"IDC_STATIC_QUALITY_PROCESS_SETTING":"轉換質量和處理設置",
"IDC_STATIC_TRANS_MODE":"轉換模式",
"IDC_RADIO_MODE_NOISE_SCALE":"降噪和放大",
"IDC_RADIO_MODE_SCALE":"放大",
"IDC_RADIO_MODE_NOISE":"降噪",
"IDC_RADIO_AUTO_SCALE":"自動降噪和放大",
"IDC_STATIC_JPEG_NOISE_LEVEL":"JPEG降噪水平",
"IDC_RADIONOISE_LEVEL1":"1級",
"IDC_RADIONOISE_LEVEL2":"2級",
"IDC_STATIC_SCALE_RATE":"放大大小",
"IDC_RADIO_SCALE_RATIO":"放大比率",
"IDC_RADIO_SCALE_WIDTH":"轉換後高度",
"IDC_RADIO_SCALE_HEIGHT":"轉換後寬度",
"IDC_STATIC_MODEL":"模型",
"IDC_RADIO_MODEL_RGB":"二次元插圖 ( RGB模型 ) ",
"IDC_RADIO_MODEL_PHOTO":"照片和動畫 ( 照片模型 ) ",
"IDC_RADIO_MODEL_Y":"二次元插圖2 ( Y模型 ) ",
"IDC_CHECK_TTA":"使用TTA模式",
"IDC_STATIC_PROCESS_SPEED_SETTING":"處理速度設置",
"IDC_STATIC_PROCESSOR":"處理器",
"IDC_RADIO_MODE_GPU":"CUDA ( cuDNN優先 )",
"IDC_RADIO_MODE_CPU":"CPU",
"IDC_STATIC_CROP_SIZE":"拆分大小",
"IDC_BUTTON_CHECK_CUDNN":"檢查cuDNN",
"IDC_BUTTON_CANCEL":"取消",
"IDC_BUTTON_EXEC":"運行",
"IDC_STATIC_LANG_UI":"界面語言",
"MessageUseProcessorMode":"使用的處理器模式: %s",
"MessageProcessTime":"處理時間: %02d:%02d:%02d.%03d",
"MessageInitTime":"初始化時間: %02d:%02d:%02d.%03d",
"MessagecuDNNCheckTime":"cuDNN檢驗時間: %02d:%02d:%02d.%03d",
"MessageTitleError":"錯誤",
"MessageScaleRateCheckError":"放大倍率必須為大於0.0的正數。",
"MessageCropSizeCheckError":"拆分大小必須為大於0.0的正數。",
"MessageInputPathCheckError":"必須指定輸入路徑。",
"MessageOutputPathCheckError":"必須指定輸出路徑。",
"MessageOutputExtCheckError":"必須指定輸出擴展名。",
"MessageInputCheckError":"指定的文件/文件夾不存在。",
"MessageOutputExtentionCheckError":"請選擇輸出擴展名。",
"MessageOutputQualityCheckError":"輸出質量設置中的值超出範圍。",
"MessageOutputDepthCheckError":"輸出位深度值無效。",
"MessageCudaNotFindError":"無法使用GPU轉換。\r\nCUDA驅動程序可能未安裝。\r\nCUDA請事先安裝CUDA驅動程序。",
"MessageCudaOldVersionError":"無法使用GPU轉換。\r\nCUDA驅動程序版本可能已過期。\r\n請先更新CUDA驅動程序。",
"MessageTransSuccess":"轉換成功。",
"MessageErrorHappen":"發生錯誤。",
"MessageCreateOutDirError":"無法創建輸出文件夾。\r\n「%s」",
"MessageCancelError":"操作被取消。",
"MessageInvalidParameterError":"參數無效。",
"MessageFailedOpenModelFileError":"無法打開模型文件。",
"MessageFailedParseModelFileError":"模型文件損壞。",
"MessageFailedConstructModelError":"神經網絡建立失敗。",
"MessageFailedOpenInputFileError":"輸入的圖像無法打開。\r\n「%s」",
"MessageFailedOpenOutputFileError":"輸出的圖像無法寫入。\r\n「%s」",
"MessageFailedProcessCaffeError":"插值處理失敗。",
"MessageTitleResult":"檢查結果",
"MessagecuDNNOK":"cuDNN可以使用。",
"MessagecuDNNNotFindError":"cuDNN無法使用。\r\n找不到「%s」。",
"MessagecuDNNOldVersionError":"cuDNN無法使用。\r\n「%s」的版本過期。請使用%s。",
"MessagecuDNNCannotCreateError":"cuDNN無法使用。\r\n無法初始化cuDNN。",
"MessagecuDNNDefautlError":"cuDNNは無法使用。",
"MessageExtStr":"指定的轉換對象擴展名(%s)",
"MessageAllFileFolder":"所有的文件和文件夾(*.*)",
"MessageTitleInputDialog":"請選擇一個文件或文件夾。"
}
`

**Comment by aruhirin** [comment]
sorry, I can't read English. This sentence is written using a translator.
I don't know the exact meaning of what you're saying.

**Comment by lizardon1995** [comment]
繁体字中国語の言語を追加することができます?
私は簡体字中国語と英文を参考にして
繁体字中国語を修正しました

Chinese_Traditional 繁体字
Chinese_Simplified 簡体字
翻訳機

**Comment by aruhirin** [comment]
I have to enter Chinese_Traditional do not appear for Chinese_Simplified.
I don't know why. Now examine the reasons.

**Comment by aruhirin** [comment]
The problem was solved.
Now creating the file.

**Comment by yoonhakcher** [comment]
BTW repair Chinese translation please :)
中国語の翻訳を修復して下さい

Reference: #10 

简化字/Simplified Chinese/簡体字
`
{
"IDC_STATIC_IO_SETTING":"输入和输出设置",
"IDC_STATIC_INPUT_PATH":"输入\r\n(文件或文件夹)",
"IDC_BUTTON_INPUT_REF":"选择",
"IDC_STATIC_OUTPUT_PATH":"输出",
"IDC_STATIC_TANS_EXT_LIST":"文件夹内进行转换的格式",
"IDC_STATIC_OUTPUT_EXT":"输出格式",
"IDC_STATIC_OUTPUT_QUALITY":"输出图像质量",
"IDC_STATIC_OUTPUT_DEPTH":"输出色彩深度",
"IDC_STATIC_QUALITY_PROCESS_SETTING":"转换的质量和处理设置",
"IDC_STATIC_TRANS_MODE":"转换模式",
"IDC_RADIO_MODE_NOISE_SCALE":"降噪和放大",
"IDC_RADIO_MODE_SCALE":"仅放大",
"IDC_RADIO_MODE_NOISE":"仅降噪",
"IDC_RADIO_AUTO_SCALE":"自动降噪和放大",
"IDC_STATIC_JPEG_NOISE_LEVEL":"JPEG 降噪等级",
"IDC_RADIONOISE_LEVEL1":"1 级",
"IDC_RADIONOISE_LEVEL2":"2 级",
"IDC_STATIC_SCALE_RATE":"放大率",
"IDC_STATIC_MODEL":"模式",
"IDC_RADIO_MODEL_RGB":"2D 插图 (RGB 模型)",
"IDC_RADIO_MODEL_PHOTO":"照片 或 动画 (Photo 模型)",
"IDC_RADIO_MODEL_Y":"2D 插图 2 (Y 模型)",
"IDC_CHECK_TTA":"TTA 模式",
"IDC_STATIC_PROCESS_SPEED_SETTING":"处理速度设置",
"IDC_STATIC_PROCESSOR":"处理器",
"IDC_RADIO_MODE_GPU":"CUDA (cuDNN 优先)",
"IDC_RADIO_MODE_CPU":"CPU",
"IDC_STATIC_CROP_SIZE":"拆分大小",
"IDC_BUTTON_CHECK_CUDNN":"cuDNN 检查",
"IDC_BUTTON_CANCEL":"取消",
"IDC_BUTTON_EXEC":"开始",
"IDC_STATIC_LANG_UI":"界面语言",
"MessageUseProcessorMode":"使用的处理模式: %s",
"MessageProcessTime":"处理时间: %02d:%02d:%02d.%03d",
"MessageInitTime":"初始化时间: %02d:%02d:%02d.%03d",
"MessagecuDNNCheckTime":"cuDNN 检查时间: %02d:%02d:%02d.%03d",
"MessageTitleError":"错误",
"MessageScaleRateCheckError":"放大倍数必须大于 0.0 的正数",
"MessageCropSizeCheckError":"拆分大小必须大于 0 的正数",
"MessageInputPathCheckError":"请设置输入路径",
"MessageOutputPathCheckError":"请设置输出路径",
"MessageOutputExtCheckError":"请设置输出格式",
"MessageInputCheckError":"输入或输出路径不存在",
"MessageOutputExtentionCheckError":"请选择输出格式",
"MessageOutputQualityCheckError":"输出图像质量过大",
"MessageOutputDepthCheckError":"输出图像色彩深度数值不正确",
"MessageCudaNotFindError":"使用 GPU 转换失败。\r\n可能是因为没有安装可调用的 CUDA 驱动。\r\n请安装驱动。",
"MessageCudaOldVersionError":"使用 GPU 转换失败。\r\n可能是因为安装的 CUDA 驱动太旧。\r\n请更新驱动。",
"MessageTransSuccess":"转换成功",
"MessageErrorHappen":"发生错误",
"MessageCreateOutDirError":"输出目录\r\n「%s」\r\n创建失败",
"MessageCancelError":"已经取消",
"MessageInvalidParameterError":"参数无效",
"MessageFailedOpenModelFileError":"模型文件无法打开",
"MessageFailedParseModelFileError":"模型文件已损坏",
"MessageFailedConstructModelError":"无法构建模型",
"MessageFailedOpenInputFileError":"无法打开输入文件「%s」",
"MessageFailedOpenOutputFileError":"无法输出文件「%s」",
"MessageFailedProcessCaffeError":"插值处理失败",
"MessageTitleResult":"结果",
"MessagecuDNNOK":"可以使用 cuDNN。",
"MessagecuDNNNotFindError":"调用 cuDNN 失败。\r\n没有发现「%s」。",
"MessagecuDNNOldVersionError":"调用 cuDNN 失败。\r\n「%s」版本太旧。请使用 %s。",
"MessagecuDNNCannotCreateError":"调用 cuDNN 失败。\r\n初始化 cuDNN 失败。",
"MessagecuDNNDefautlError":"调用 cuDNN 失败",
"MessageExtStr":"输入文件扩展名 (%s)",
"MessageAllFileFolder":"所有文件和文件夹 (*.*)",
"MessageTitleInputDialog":"请选择输入文件或文件夹"
}
`

正體字/Traditional Chinese/繁体字
`{
"IDC_STATIC_IO_SETTING":"輸入和輸出設定",
"IDC_STATIC_INPUT_PATH":"輸入\r\n(檔案或資料夾)",
"IDC_BUTTON_INPUT_REF":"選擇",
"IDC_STATIC_OUTPUT_PATH":"輸出",
"IDC_STATIC_TANS_EXT_LIST":"資料夾內進行轉換的格式",
"IDC_STATIC_OUTPUT_EXT":"輸出格式",
"IDC_STATIC_OUTPUT_QUALITY":"輸出影象質量",
"IDC_STATIC_OUTPUT_DEPTH":"輸出色彩深度",
"IDC_STATIC_QUALITY_PROCESS_SETTING":"轉換的質量和處理設定",
"IDC_STATIC_TRANS_MODE":"轉換模式",
"IDC_RADIO_MODE_NOISE_SCALE":"降噪和放大",
"IDC_RADIO_MODE_SCALE":"僅放大",
"IDC_RADIO_MODE_NOISE":"僅降噪",
"IDC_RADIO_AUTO_SCALE":"自動降噪和放大",
"IDC_STATIC_JPEG_NOISE_LEVEL":"JPEG 降噪等級",
"IDC_RADIONOISE_LEVEL1":"1 級",
"IDC_RADIONOISE_LEVEL2":"2 級",
"IDC_STATIC_SCALE_RATE":"放大率",
"IDC_STATIC_MODEL":"模式",
"IDC_RADIO_MODEL_RGB":"2D 插圖 (RGB 模型)",
"IDC_RADIO_MODEL_PHOTO":"照片 或 動畫 (Photo 模型)",
"IDC_RADIO_MODEL_Y":"2D 插圖 2 (Y 模型)",
"IDC_CHECK_TTA":"TTA 模式",
"IDC_STATIC_PROCESS_SPEED_SETTING":"處理速度設定",
"IDC_STATIC_PROCESSOR":"處理器",
"IDC_RADIO_MODE_GPU":"CUDA (cuDNN 優先)",
"IDC_RADIO_MODE_CPU":"CPU",
"IDC_STATIC_CROP_SIZE":"拆分大小",
"IDC_BUTTON_CHECK_CUDNN":"cuDNN 檢查",
"IDC_BUTTON_CANCEL":"取消",
"IDC_BUTTON_EXEC":"開始",
"IDC_STATIC_LANG_UI":"介面語言",
"MessageUseProcessorMode":"使用的處理模式: %s",
"MessageProcessTime":"處理時間: %02d:%02d:%02d.%03d",
"MessageInitTime":"初始化時間: %02d:%02d:%02d.%03d",
"MessagecuDNNCheckTime":"cuDNN 檢查時間: %02d:%02d:%02d.%03d",
"MessageTitleError":"錯誤",
"MessageScaleRateCheckError":"放大倍數必須大於 0.0 的正數",
"MessageCropSizeCheckError":"拆分大小必須大於 0 的正數",
"MessageInputPathCheckError":"請設定輸入路徑",
"MessageOutputPathCheckError":"請設定輸出路徑",
"MessageOutputExtCheckError":"請設定輸出格式",
"MessageInputCheckError":"輸入或輸出路徑不存在",
"MessageOutputExtentionCheckError":"請選擇輸出格式",
"MessageOutputQualityCheckError":"輸出影象質量過大",
"MessageOutputDepthCheckError":"輸出影象色彩深度數值不正確",
"MessageCudaNotFindError":"使用 GPU 轉換失敗。\r\n可能是因為沒有安裝可呼叫的 CUDA 驅動。\r\n請安裝驅動。",
"MessageCudaOldVersionError":"使用 GPU 轉換失敗。\r\n可能是因為安裝的 CUDA 驅動太舊。\r\n請更新驅動。",
"MessageTransSuccess":"轉換成功",
"MessageErrorHappen":"發生錯誤",
"MessageCreateOutDirError":"輸出目錄\r\n「%s」\r\n創建失敗",
"MessageCancelError":"已經取消",
"MessageInvalidParameterError":"參數無效",
"MessageFailedOpenModelFileError":"模型檔案無法開啟",
"MessageFailedParseModelFileError":"模型檔案已損壞",
"MessageFailedConstructModelError":"無法構建模型",
"MessageFailedOpenInputFileError":"無法開啟輸入檔案「%s」",
"MessageFailedOpenOutputFileError":"無法輸出檔案「%s」",
"MessageFailedProcessCaffeError":"插值處理失敗",
"MessageTitleResult":"結果",
"MessagecuDNNOK":"可以使用 cuDNN。",
"MessagecuDNNNotFindError":"呼叫 cuDNN 失敗。\r\n沒有發現「%s」。",
"MessagecuDNNOldVersionError":"呼叫 cuDNN 失敗。\r\n「%s」版本太舊。請使用 %s。",
"MessagecuDNNCannotCreateError":"呼叫 cuDNN 失敗。\r\n初始化 cuDNN 失敗。",
"MessagecuDNNDefautlError":"呼叫 cuDNN 失敗",
"MessageExtStr":"輸入副檔名 (%s)",
"MessageAllFileFolder":"所有檔案和資料夾 (*.*)",
"MessageTitleInputDialog":"請選擇輸入檔案或資料夾"
}
`

**Comment by aruhirin** [comment]
Please tell me what is wrong.
It is difficult to find.

**Comment by yoonhakcher** [comment]
Such as

> cuDNNは無法使用。
Has a Japanese only character, etc.

**Comment by yoonhakcher** [comment]
Also fixed some grammatical mistakes.
文法上の間違いを修正しました。

**Comment by aruhirin** [comment]
혹시 한국인인가요? 위에 올리신 중국어는 버전이 최신 버전 항목이 아니라서 일일이 찾아서 고쳐야합니다. 최신 버전 1.1.2.1 로 새로 추가된 기능까지 다 확인해주세요.
Please fix in the latest version of the file.

**Comment by aruhirin** [comment]
Please fix in the latest version of the file.
Including the newly added features will please fix.

**Comment by yoonhakcher** [comment]
Updated. 
I try to apply it to the program, but it doesn't work:_

**Comment by aruhirin** [comment]
適用してみました。そして出力も確認しました。
[lang.zip](https://github.com/lltcggie/waifu2x-caffe/files/184144/lang.zip)
ver 1.1.2.1

**Comment by yoonhakcher** [comment]
ありがとうございます:)

**Comment by lizardon1995** [comment]
Mode = 模型 / 模式 / 模組

3種類の意味に分けて、私は繁体字の誤りを引き続き検査します

**Comment by aruhirin** [comment]
I can't understand Chinese, leave it.

**Comment by lizardon1995** [comment]
> {
> "IDC_STATIC_IO_SETTING":"輸入和輸出設置",
> "IDC_STATIC_INPUT_PATH":"輸入路徑\r\n(可使用文件夾)",
> "IDC_BUTTON_INPUT_REF":"瀏覽文件",
> "IDC_STATIC_OUTPUT_PATH":"輸出路徑",
> "IDC_STATIC_TANS_EXT_LIST":"在文件夾中轉換的副檔名",
> "IDC_STATIC_OUTPUT_EXT":"輸出副檔名",
> "IDC_STATIC_OUTPUT_QUALITY":"輸出質量設置",
> "IDC_STATIC_OUTPUT_DEPTH":"輸出位元深度",
> "IDC_STATIC_AUTO_START":"自動開始設定",
> "IDC_RADIO_AUTO_START_NONE":"不自動開始",
> "IDC_RADIO_AUTO_START_ONE":"輸入文件",
> "IDC_RADIO_AUTO_START_MULTI":"輸入多個文件或文件夾",
> "IDC_STATIC_QUALITY_PROCESS_SETTING":"轉換質量和處理設置",
> "IDC_STATIC_TRANS_MODE":"轉換模式",
> "IDC_RADIO_MODE_NOISE_SCALE":"降噪和放大",
> "IDC_RADIO_MODE_SCALE":"放大",
> "IDC_RADIO_MODE_NOISE":"降噪",
> "IDC_RADIO_AUTO_SCALE":"自動降噪和放大",
> "IDC_STATIC_JPEG_NOISE_LEVEL":"JPEG降噪水平",
> "IDC_RADIONOISE_LEVEL1":"等級1",
> "IDC_RADIONOISE_LEVEL2":"等級2",
> "IDC_STATIC_SCALE_RATE":"放大大小",
> "IDC_RADIO_SCALE_RATIO":"放大比率",
> "IDC_RADIO_SCALE_WIDTH":"轉換後高度",
> "IDC_RADIO_SCALE_HEIGHT":"轉換後寬度",
> "IDC_STATIC_MODEL":"模式",
> "IDC_RADIO_MODEL_RGB":"二次元插圖 ( RGB模式 ) ",
> "IDC_RADIO_MODEL_PHOTO":"照片和動畫 ( 照片模式 ) ",
> "IDC_RADIO_MODEL_Y":"二次元插圖2 ( Y模式 ) ",
> "IDC_CHECK_TTA":"使用TTA模式",
> "IDC_STATIC_PROCESS_SPEED_SETTING":"處理速度設置",
> "IDC_STATIC_PROCESSOR":"處理器",
> "IDC_RADIO_MODE_GPU":"CUDA ( cuDNN優先 )",
> "IDC_RADIO_MODE_CPU":"CPU",
> "IDC_STATIC_CROP_SIZE":"拆分大小",
> "IDC_BUTTON_CHECK_CUDNN":"檢查cuDNN",
> "IDC_BUTTON_CANCEL":"取消",
> "IDC_BUTTON_EXEC":"運行",
> "IDC_STATIC_LANG_UI":"界面語言",
> "MessageUseProcessorMode":"使用的處理器模式: %s",
> "MessageProcessTime":"處理時間: %02d:%02d:%02d.%03d",
> "MessageInitTime":"初始化時間: %02d:%02d:%02d.%03d",
> "MessagecuDNNCheckTime":"cuDNN檢驗時間: %02d:%02d:%02d.%03d",
> "MessageTitleError":"錯誤",
> "MessageScaleRateCheckError":"放大倍率必須為大於0.0的正數",
> "MessageScaleWidthCheckError":"放大尺寸必須大於0的正數",
> "MessageCropSizeCheckError":"拆分大小必須為大於0.0的正數",
> "MessageInputPathCheckError":"必須指定輸入路徑",
> "MessageOutputPathCheckError":"必須指定輸出路徑",
> "MessageOutputExtCheckError":"必須指定輸出副檔名",
> "MessageInputCheckError":"指定的文件/文件夾不存在",
> "MessageOutputExtentionCheckError":"請選擇輸出副檔名",
> "MessageOutputQualityCheckError":"輸出質量設置中的值超出範圍",
> "MessageOutputDepthCheckError":"輸出位元深度值無效",
> "MessageCudaNotFindError":"無法使用GPU轉換\r\nCUDA驅動程序可能未安裝\r\nCUDA請事先安裝CUDA驅動程序",
> "MessageCudaOldVersionError":"無法使用GPU轉換\r\nCUDA驅動程序版本可能已過期\r\n請先更新CUDA驅動程序",
> "MessageTransSuccess":"轉換成功",
> "MessageErrorHappen":"發生錯誤",
> "MessageCreateOutDirError":"無法創建輸出文件夾\r\n「%s」",
> "MessageCancelError":"操作被取消",
> "MessageInvalidParameterError":"參數無效",
> "MessageFailedOpenModelFileError":"無法打開模組文件",
> "MessageFailedParseModelFileError":"模組的文件損壞",
> "MessageFailedConstructModelError":"神經網絡建立失敗",
> "MessageFailedOpenInputFileError":"輸入的圖像無法打開\r\n「%s」",
> "MessageFailedOpenOutputFileError":"輸出的圖像無法寫入\r\n「%s」",
> "MessageFailedProcessCaffeError":"插值處理失敗",
> "MessageTitleResult":"檢查結果",
> "MessagecuDNNOK":"cuDNN可以使用",
> "MessagecuDNNNotFindError":"cuDNN無法使用\r\n找不到「%s」",
> "MessagecuDNNOldVersionError":"cuDNN無法使用\r\n「%s」的版本過期請使用%s",
> "MessagecuDNNCannotCreateError":"cuDNN無法使用\r\n無法初始化cuDNN",
> "MessagecuDNNDefautlError":"cuDNN預設無法使用",
> "MessageExtStr":"指定的轉換對象副檔名(%s)",
> "MessageAllFileFolder":"所有的文件和文件夾(.)",
> "MessageTitleInputDialog":"請選擇一個文件或文件夾",
> "MessageTimeLeftUnkown":"預估剩餘時間: 未知",
> "MessageTimeLeft":"預估剩餘時間"
> }
>

**Comment by yoonhakcher** [comment]
unified to 模式?

**Comment by aruhirin** [comment]
Updated.
[lang.zip](https://github.com/lltcggie/waifu2x-caffe/files/184170/lang.zip)

**Comment by lizardon1995** [comment]
模式 :方法を使います
模組 :資料の処理する過程あるいはシステム設計の過程を多くの部分あるいは段階に分けて、それぞれは一部はすぐ１つのモジュールと称します。

どんな種類の良いあなた達は決定しましょう :)

**Comment by aruhirin** [comment]
説明によるとmodeは「模式」、modelは「模組」のようですね。
まあ、私は中国語の使い手ではないから・・・決めたらまた書いてください。

**Comment by lizardon1995** [comment]
Yes. あなたの理解は間違いがありません

**Comment by MaverickTse** [comment]
ちょっと違います：
有點不對:
mode : 模式
model : 模型
module : 模組/組件

**Comment by lizardon1995** [comment]
我自己有點搞混了...
私自身は少し混乱しました...

**Comment by MaverickTse** [comment]
例え”RGB model”、翻訳すると：
RGB model = Use RGB model　→　使用RGB模型

もし”RGB mode”なら　→RGB 模式

でも意味的に大差ないからどうでもいい

**Comment by lizardon1995** [comment]
模型 = ガンダム

**Comment by aruhirin** [comment]
Mobile suitですか・・・？

**Comment by MaverickTse** [comment]
冗談やめよ。他の人が誤解したら悪い…
ガンダム：高達
ガンプラ：膠製高達模型

**Comment by lizardon1995** [comment]
模型: 実物の正体をまねて、一定割合によって製造するサンプルを縮小します。通常は多く展覧あるいは実験に用います。例えば：「科学博物館の中でたくさんの飛行機の模型を展覧します。

だから 模型 = ガンダム 連想しますw

すみません

**Comment by lizardon1995** [comment]
香港、台湾、中国の用語はすべて違いがあります

**Comment by aruhirin** [comment]
ああ、そういう意味でしたか。
いきなりガンダムが出てびっくりしました。
とにかく私は用事がありまして、決められたら書いてください。ファイルを作ってあげます。

**Comment by MaverickTse** [comment]
別に今そのまま良いと思う

**Comment by lizardon1995** [comment]
三人感謝します

**Comment by lltcggie** [comment]
@aruhirin @lizardon1995 @yoonhakcher @MaverickTse
皆様ありがとうございます。
READMEの修正、翻訳の更新、出力画質設定保存のバグの修正を行いました。
