### ISSUE TITLE
Immediate crash when more than 1 GPU present

### ISSUE THREAD

**Issue by 78Alpha** [lltcggie/waifu2x-caffe#200]
Attempted to denoise a 512x512 image to make sure this was the issue.

Before today, I only had an RTX 2060, it worked flawlessly. However, after installing a second GPU (GTX 1650) as a co-CUDA processor/general GPU.

The application crashes with error...

_A fatal error has occured
There is a possibility the split size is too large_

I can rule that right out, since the split size is default and is running on the same RTX 2060, crashes when run on the GTX 1650 as well.

**Comment by lltcggie** [comment]
ver 1.2.0.4でCUDA ToolkitとcuDNNを更新したので直ったと思われます。

**Comment by 78Alpha** [comment]
Gave it a try later on and it's all fixed. Likely caused by a driver issue as it was fixed by reinstalling windows and using a development driver.
