### ISSUE TITLE
waifu2x not recognizing CUDA driver :(

### ISSUE THREAD

**Issue by Double44** [lltcggie/waifu2x-caffe#21]
![ade0zy8l](https://cloud.githubusercontent.com/assets/6753152/14300219/33074fe2-fb4c-11e5-9f48-92d8d5d9e606.jpg)

![capture6](https://cloud.githubusercontent.com/assets/6753152/14300506/0932f5a2-fb4e-11e5-8f07-a5dbab8255c6.PNG)

![capture](https://cloud.githubusercontent.com/assets/6753152/14301171/cae54b56-fb52-11e5-849c-b1a004225bdb.PNG)

[NVIDIA CUDA](https://developer.nvidia.com/cuda-downloads)
![ebsci8x](https://cloud.githubusercontent.com/assets/6753152/14300705/66a95356-fb4f-11e5-872c-0c8f496f633e.png)

![capture2](https://cloud.githubusercontent.com/assets/6753152/14301094/35655044-fb52-11e5-93b1-10f9466e42d4.PNG)

![capture](https://cloud.githubusercontent.com/assets/6753152/14301052/e046ab9e-fb51-11e5-8d81-81408625f911.PNG)

![capture](https://cloud.githubusercontent.com/assets/6753152/14300182/ec6490c2-fb4b-11e5-9fe6-dc6ac22950d8.PNG)

???

**Comment by Double44** [comment]
Shit, i just realized I downloaded the wrong file. What the hell did i just install lol
https://developer.nvidia.com/cudnn

**Comment by Double44** [comment]
Okay, so I downloaded cuDNN and dropped it in the waifu2x directory...
![capture](https://cloud.githubusercontent.com/assets/6753152/14302377/52230ae0-fb5d-11e5-86d6-ced47ac1aaac.PNG)

...but I'm still getting this error :(
![capture2](https://cloud.githubusercontent.com/assets/6753152/14302381/57e3fb92-fb5d-11e5-98b4-307ab6f71c9f.PNG)
what am i doing wrong this time???

**Comment by HolyWu** [comment]
cuDNN needs a CUDA GPU that has Compute Capability of at least **3.0**. GeForce G105M's Compute Capability is only **1.1**.

**Comment by lltcggie** [comment]
すいません、要求環境には書かれていませんでしたがCUDAで計算するにはCompute Capability 2.0以上のGPUが必要です。
@HolyWu さんが書かれている通りGeForce G105MのCompute Capabilityは1.1なので、CUDAで計算することは出来ません。

**Comment by Double44** [comment]
Aww man, you guys know how to ruin someone's day. The cpu takes about four minutes to convert a single image, was hoping to speed that up somehow :(

**Comment by HolyWu** [comment]
You can try another [waifu2x converter](https://github.com/tanakamura/waifu2x-converter-cpp) that supports OpenCL and SIMD optimization.

**Comment by Double44** [comment]
I will give that one a try, thank you for all your help :]

**Comment by Veshurik** [comment]
EM... So, that program doesn't work on AMD?
I tried to run it with CPU, but... Nothing happens, estimated time is endless... I don't know what to do.
