### ISSUE TITLE
CUDA Toolkit security issue

### ISSUE THREAD

**Issue by tsulala** [lltcggie/waifu2x-caffe#210]
There appears to be a vulnerability that affects all versions of CUDA Toolkit 11.1.1 and earlier.
source: https://nvidia.custhelp.com/app/answers/detail/a_id/5094

Does this security issue affect waifu2x-caffe?

**Comment by nagadomi** [comment]
I don't think so. waifu2x-caffe does not use NVJPEG API.

**Comment by tsulala** [comment]
I see. thank you :)
