### ISSUE TITLE
How to upscale on Geforce GT 525M

### ISSUE THREAD

**Issue by BlitGaming** [lltcggie/waifu2x-caffe#215]
Can I upscale photo using waifu2x-caffe on NVIDIA Geforce GT 525M graphics card and on which version? (CUDA Compute Capability version: 2.1)

**Comment by 31ank** [comment]
i'm not a dev but I had problems with my GTX960M, you can just go into settings and use your cpu instead of gpu to upscale, it takes a little bit longer but still works

**Comment by Zergei** [comment]
> Can I upscale photo using waifu2x-caffe on NVIDIA Geforce GT 525M graphics card and on which version? (CUDA Compute Capability version: 2.1)

try this version of Waifu2x-Caffe version 1.1.8.4 which has the cudnn in the 8.0 version which uses Compute Capability 2.0 new versions of Waifu uses Compute Capability 3.5 ill be testing other versions until i know which is the last version we can safetly use

[https://drive.google.com/file/d/1syyxwON8Drjo8DJl1jdq9gJaKfpQ2uql/view?usp=sharing](url)

**Comment by BlitGaming** [comment]
works with the old version waifu2x
