### ISSUE TITLE
Error cuDNN

### ISSUE THREAD

**Issue by Pantyhose-X** [lltcggie/waifu2x-caffe#217]
Error CUDA(uses cuDNN)
* Error_Log file created at: 2021/04/05 08:41:58
Running on machine: DESKTOP
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0405 08:41:58.613559  1072 cudnn_conv_layer.cpp:54] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

![Capture](https://user-images.githubusercontent.com/42504385/113526249-72d16980-960d-11eb-893d-22882355bae5.JPG)

**Comment by XxRoMKxX** [comment]
same problem
