### ISSUE TITLE
エラー: モデルファイルが開けませんでした

### ISSUE THREAD

**Issue by wizardforcel** [lltcggie/waifu2x-caffe#235]
When I invoke the cli tool from Python with `subprocess.Popen(shell=True)`，it shows this error. But it's OK through PowerShell. What;s wrong?

**Comment by nagadomi** [comment]
The error message means that the model file cannot be opened.
Perhaps you need to set the *current working directory* for the application.
`subprocess.Popen(shell=True, cwd=waifu2x_bin_dir)`
or specify the `--model_dir` option.
