### ISSUE TITLE
About Ultra low resolution

### ISSUE THREAD

**Issue by lonerfscar** [lltcggie/waifu2x-caffe#24]
Apologies for my poor English, Thanks for your project.
I'm trying to use Waifu2X on M.U.G.E.N chars which was almost jagged.
And there is another tool named 2xScale，under ultra low resolution Waifu2X have better fill but they have more smooth edges.
here is a picture.
http://r5.loli.io/uaeY7j.png
Maybe in further Waifu2X can also has a ultra low resolution mode like that ,of course this is just my personal opinion,thanks for your contribution.

**Comment by lltcggie** [comment]
後で返事を書こうと思ってすっかり忘れていました。すいません…
このソフトは https://github.com/nagadomi/waifu2x の移植なので、そちらでIssuesを立てると何かいい案が見つかるかもしれません。
