### ISSUE TITLE
Training Hints

### ISSUE THREAD

**Issue by invisiblearts** [lltcggie/waifu2x-caffe#3]
It seems that the prototxt has already contained something useful for training. There still exists, however, some work needed to be done to train another model using native caffe interface.
I would appreciate it if the project would provide some proto texts essential for training and even scripts. Some basic hints are also fine.

**Comment by lltcggie** [comment]
prototxtのトレーニングに関する記述はCaffeの使用方法を探っている最中に適当に書いたもので、Caffeのトレーニングに関する知識はあまりありません。
なので申し訳ありませんがアドバイスできるようなこともないです…

**Comment by invisiblearts** [comment]
Would you please use English? 'Cause I'm Chinese and have to rely on Google Translate..
To be more specific, I hope for a solver prototxt. If you're not interested in that, maybe I can try to write one and create a PR. (Though I'm not so familiar with Caffe yet..)

**Comment by Heiseikiseki** [comment]
The author said he doesn't have any training knowledge of caffe so he can't help you.
