### ISSUE TITLE
Transparency lost in some images

### ISSUE THREAD

**Issue by BigheadSMZ** [lltcggie/waifu2x-caffe#30]
Not sure why but sometimes the transparency is not kept in the result. I'm not sure exactly what causes it, but it happens for some images and not others.
http://imgur.com/a/7ppIu

Is there a reason this happens that I am not aware of?

**Comment by nagadomi** [comment]
Is that image from waifu2x.udp.jp?
It seems that waifu2x.udp.jp has bug in grayscale+alpha image (GrayscaleMatte type).
And it is caused by the old version of GraphicsMagick.

**Comment by BigheadSMZ** [comment]
No this is using waifu2x-caffe ver 1.1.3.2 from here:
https://github.com/lltcggie/waifu2x-caffe/releases

I tried both CLI (waifu2x-caffe-cui.exe) and GUI (waifu2x-caffe.exe) along with multiple options and the result is the same.

**Comment by nagadomi** [comment]
Oh, sorry. Then that is a issue of waifu2x-caffe.
It seems that waifu2x-caffe does not support grayscale image with alpha channel.[ sauce](https://github.com/lltcggie/waifu2x-caffe/blob/509e393298da2ab25b7303dc844b232f7b59eaaf/common/waifu2x.cpp#L564)

**Comment by lltcggie** [comment]
申し訳ありませんが、OpenCVがアルファ付きグレースケール画像に対応していないようなので、現在のwaifu2x-caffeでは対応することが出来ません。
