### ISSUE TITLE
UpRGB model conversion artifact or feature?

### ISSUE THREAD

**Issue by YukiSakuma** [lltcggie/waifu2x-caffe#34]
I am using 1.1.5 to test the new RGB model of waifu2x caffe and I notice some differences between RGB and UpRGB
Test image:
![09019cd4-ac7d-11e5-818d-98d769465384](https://cloud.githubusercontent.com/assets/16185735/16636926/d5e45f98-440d-11e6-893c-bd805b8695c5.png)
(RGB)(noise)(Level1)(tta)(RGB)(scale)(x8.000000)
Looks smooth
![rgb](https://cloud.githubusercontent.com/assets/16185735/16637033/9790feb2-440e-11e6-8e03-872e59ac8474.png)
vs
(UpRGB)(noise)(Level1)(tta)(UpRGB)(scale)(x8.000000)
![uprgb](https://cloud.githubusercontent.com/assets/16185735/16637053/c3296e6a-440e-11e6-8a4f-71f6aac2b1da.png)
Looks like jagged lines is this an error or a feature of UpRGB?

**Comment by nagadomi** [comment]
That is a feature of upconv_7 models. waifu2x-caffe is not related.
It seems that upconv_7's first noise reduction result is sharper than old vgg 7 models.

**Comment by YukiSakuma** [comment]
I see I tried RGB noise then UpRGB magnify, the jagged lines disappeared so I wonder how UpRGB/UpPhoto is different from RGB/Photo when scaling/magnifying?

**Comment by nagadomi** [comment]
model difference is:

RGB/Photo
 1. image upscaling with nearest neighbor algorithm (very simple upscaler)
 2. fixing poor upscaled image with neural networks

UpRGB/UpPhoto
 1. directly image upscaling with neural networks (end-to-end optimization)

processing details is.. Neural networks only knows :disappointed:. I have as impression that UpRGB/UpPhoto is very sensitive to the input image pixels. The average quality of UpRGB/UpPhoto is better than RGB/Photo but sometimes it makes weird results.

**Comment by lltcggie** [comment]
一応変換の適用ミスがないか調べてみましたが特にそういうことはなさそうだったので、このIssueは閉じます。
