### ISSUE TITLE
Error output images

### ISSUE THREAD

**Issue by wwb443872831** [lltcggie/waifu2x-caffe#35]
This is original images:
[original images zip](https://github.com/wwb443872831/PublicStorge/raw/master/original_images.zip)
Output iamges:
[output images zip](https://github.com/wwb443872831/PublicStorge/raw/master/%40Ariesbto_EV122A(UpRGB)(auto_scale)(Level2)(x2.000000).zip)

**Comment by wwb443872831** [comment]
This error output is always appearing,no matter I changed the output settings or application settings.

**Comment by lltcggie** [comment]
修正しました
