### ISSUE TITLE
JPEG sequence issue

### ISSUE THREAD

**Issue by TheDarkWarLord** [lltcggie/waifu2x-caffe#36]
When I try to select a JPEG sequence the program automatically shuts down. It crashes when I select between 500-1000 JPEG pictures.

**Comment by lltcggie** [comment]
すいません、僕の英語力が足りないせいか、何をした時にクラッシュしたのかよくわかりません。
もう少し具体的な内容と、使用したプロセッサー、環境、変換内容などを書いてください。
あと、エラーログ(error_log_～)がある場合はその内容を書いていただけると、原因を特定しやすくなります。

**Comment by TheDarkWarLord** [comment]
I couldn't find the error log. I used these settings http://prntscr.com/bpzy08 .
CPU: Intel Core I7 4790. GPU: GTX 970

**Comment by MaverickTse** [comment]
和訳：『500～1000枚JPEGを纏めて処理しようと落ちました』

**Comment by lltcggie** [comment]
情報と和訳をありがとうございます。
少し調べてみます。

**Comment by lltcggie** [comment]
同じ変換条件で700枚くらいのPNG画像(サイズは311x569)を変換しました。
画像をまとめてGUIにドロップして指定して変換、画像が入ったフォルダを指定して変換のどちらもやりましたが、クラッシュしませんでした。
CPU: Intel Core i7-2600K. GPU: GTX 980 Ti. Memory: 16GB

**Comment by TheDarkWarLord** [comment]
https://youtu.be/cjzabzji2qE 

English:
I selected more then 500 pictures and it crashes. It shuts the program down and tries to resolve the problem, but nothing happens. 

Japanese (Google Translate): 
私はもっとして500の画像を選択し、それがクラッシュします。これはプログラムをシャットダウンし、問題を解決しようとしますが、何も起こりません。

**Comment by lltcggie** [comment]
動画まで撮っていただきありがとうございます。
参照ダイアログの動作は確かめていませんでした。
仕事が終わったら調べてみます。

**Comment by lltcggie** [comment]
修正しました
