### ISSUE TITLE
Translation Update

### ISSUE THREAD

**Issue by yoonhakcher** [lltcggie/waifu2x-caffe#37]
Simplified Chinese - 简体中文
> {
> "IDC_STATIC_IO_SETTING":"输入和输出设置",
> "IDC_STATIC_INPUT_PATH":"输入\r\n(文件或文件夹)",
> "IDC_BUTTON_INPUT_REF":"浏览...",
> "IDC_STATIC_OUTPUT_PATH":"输出",
> "IDC_STATIC_TANS_EXT_LIST":"文件夹内进行转换的格式",
> "IDC_STATIC_OUTPUT_EXT":"输出格式",
> "IDC_STATIC_OUTPUT_QUALITY":"输出图像质量",
> "IDC_STATIC_OUTPUT_DEPTH":"输出色彩深度",
> "IDC_STATIC_AUTO_START":"输入目录时的自动转换设置",
> "IDC_RADIO_AUTO_START_NONE":"不启用",
> "IDC_RADIO_AUTO_START_ONE":"输入单个文件时启用",
> "IDC_RADIO_AUTO_START_MULTI":"输入文件夹或多个文件时启用",
> "IDC_STATIC_QUALITY_PROCESS_SETTING":"质量和处理设置",
> "IDC_STATIC_TRANS_MODE":"转换模式",
> "IDC_RADIO_MODE_NOISE_SCALE":"降噪和放大",
> "IDC_RADIO_MODE_SCALE":"仅放大",
> "IDC_RADIO_MODE_NOISE":"仅降噪",
> "IDC_RADIO_AUTO_SCALE":"自动降噪和放大",
> "IDC_STATIC_JPEG_NOISE_LEVEL":"降噪等级",
> "IDC_RADIONOISE_LEVEL1":"1 级",
> "IDC_RADIONOISE_LEVEL2":"2 级",
> "IDC_RADIONOISE_LEVEL3":"3 级",
> "IDC_STATIC_SCALE_RATE":"放大尺寸",
> "IDC_RADIO_SCALE_RATIO":"放大倍率",
> "IDC_RADIO_SCALE_WIDTH":"放大后宽度",
> "IDC_RADIO_SCALE_HEIGHT":"放大后长度",
> "IDC_STATIC_MODEL":"模式",
> "IDC_RADIO_MODEL_RGB":"2D 插图 — RGB 模型",
> "IDC_RADIO_MODEL_PHOTO":"照片或动画 — Photo 模型",
> "IDC_RADIO_MODEL_Y":"2D 插图 — Y 模型",
> "IDC_CHECK_TTA":"TTA 模式",
> "IDC_STATIC_PROCESS_SPEED_SETTING":"处理速度设置",
> "IDC_STATIC_PROCESSOR":"处理器",
> "IDC_RADIO_MODE_GPU":"CUDA (cuDNN 优先)",
> "IDC_RADIO_MODE_CPU":"CPU",
> "IDC_STATIC_CROP_SIZE":"拆分大小",
> "IDC_BUTTON_CHECK_CUDNN":"cuDNN 检查",
> "IDC_BUTTON_CANCEL":"取消",
> "IDC_BUTTON_EXEC":"开始",
> "IDC_STATIC_LANG_UI":"界面语言",
> "IDC_BUTTON_OUTPUT_REF":"选择",
> "IDC_BUTTON_APP_SETTING":"应用设置...",
> "IDC_BUTTON_CLEAR_OUTPUT_DIR":"重设输出路径",
> "IDC_STATIC_ARG_START":"带参数的启动设置",
> "IDC_CHECK_ARG_START_AUTO":"启动时开始转换",
> "IDC_CHECK_ARG_START_SUCCESS_FINISH":"成功后自动退出",
> "IDC_STATIC_INPUT_DIR_FIX":"默认输入文件夹",
> "IDC_STATIC_OUTPUT_DIR_FIX":"默认输出文件夹",
> "IDC_CHECK_OUTPUT_NO_OVERWIRITE":"输出文件不覆盖",
> "MessageUseProcessorMode":"使用的处理模式: %s",
> "MessageProcessTime":"处理时间: %02d:%02d:%02d.%03d",
> "MessageInitTime":"初始化时间: %02d:%02d:%02d.%03d",
> "MessagecuDNNCheckTime":"cuDNN 检查时间: %02d:%02d:%02d.%03d",
> "MessageTitleError":"错误",
> "MessageScaleRateCheckError":"放大倍率必须大于 0 的正数",
> "MessageScaleWidthCheckError":"放大尺寸必须大于 0 的正数",
> "MessageCropSizeCheckError":"拆分大小必须大于 0 的正数",
> "MessageInputPathCheckError":"请设置输入路径",
> "MessageOutputPathCheckError":"请设置输出路径",
> "MessageOutputExtCheckError":"请设置输出格式",
> "MessageInputCheckError":"输入或输出路径不存在",
> "MessageOutputExtentionCheckError":"请选择输出格式",
> "MessageOutputQualityCheckError":"输出图像质量过大",
> "MessageOutputDepthCheckError":"输出图像色彩深度数值不正确",
> "MessageCudaNotFindError":"使用 GPU 转换失败。\r\n可能是因为没有安装可调用的 CUDA 驱动。\r\n请安装驱动。",
> "MessageCudaOldVersionError":"使用 GPU 转换失败。\r\n可能是因为安装的 CUDA 驱动太旧。\r\n请更新驱动。",
> "MessageTransSuccess":"转换成功",
> "MessageErrorHappen":"发生错误",
> "MessageCreateOutDirError":"输出目录\r\n「%s」\r\n创建失败",
> "MessageCancelError":"已经取消",
> "MessageInvalidParameterError":"参数无效",
> "MessageFailedOpenModelFileError":"模型文件无法打开",
> "MessageFailedParseModelFileError":"模型文件已损坏",
> "MessageFailedConstructModelError":"无法构建模型",
> "MessageFailedOpenInputFileError":"无法打开输入文件「%s」",
> "MessageFailedOpenOutputFileError":"无法输出文件「%s」",
> "MessageFailedProcessCaffeError":"插值处理失败",
> "MessageTitleResult":"结果",
> "MessagecuDNNOK":"可以使用 cuDNN。",
> "MessagecuDNNNotFindError":"调用 cuDNN 失败。\r\n没有发现「%s」。",
> "MessagecuDNNOldVersionError":"调用 cuDNN 失败。\r\n「%s」版本太旧。请使用 %s。",
> "MessagecuDNNCannotCreateError":"调用 cuDNN 失败。\r\n初始化 cuDNN 失败。",
> "MessagecuDNNDefautlError":"调用 cuDNN 失败",
> "MessageExtStr":"输入文件扩展名 (%s)",
> "MessageAllFileFolder":"所有文件和文件夹 (.)",
> "MessageTitleInputDialog":"请选择输入文件或文件夹",
> "MessageTimeLeftUnkown":"估计剩余时间: 未知",
> "MessageTimeLeft":"估计剩余时间",
> "MessageNoOverwrite":"此位置已经包含同名文件: %s",
> "MessageCudaOldDeviceError":"CUDA 组件版本太旧。\r\n请使用 rnCompute Capability 2.0 以上版本。",
> "OK":"确定",
> "Cancel":"取消"
> "IDC_STATIC_USE_GPU_NO":"GPU 相关性",
> "IDC_RADIO_MODEL_UPCONV_RGB":"2D 插图 — UpRGB 模型",
> "IDC_RADIO_MODEL_UPCONV_PHOTO":"照片或动画 — UpPhoto 模型",
> "MessageLogFatalError":"发生了致命错误。\r\n分割尺寸可能过大。"
> }

**Comment by yoonhakcher** [comment]
Incidentally, I think the display name of Traditional Chinese at LangList.txt was typed in Simplified.
I think 
> 繁體中文
or
> 正體中文
are more correct.

**Comment by lltcggie** [comment]
ありがとうございます。
更新しました。

**Comment by yoonhakcher** [comment]
Minor fixes

> "IDC_BUTTON_OUTPUT_REF":""浏览...",

**Comment by lltcggie** [comment]
修正しました。 5ed4e1665e891769698ddbd1accde31da0060f90

**Comment by yoonhakcher** [comment]
Update

> "IDC_RADIO_SCALE_WIDTH_HEIGHT":"放大后长宽",

**Comment by yoonhakcher** [comment]
@lltcggie Excuse me?

**Comment by lltcggie** [comment]
すいません、見落としてました。
修正しました https://github.com/lltcggie/waifu2x-caffe/commit/5b98bda53ce4f5e890bd129698f402be9e0a375a

**Comment by yoonhakcher** [comment]
Update for 1.1.9: 
```
"IDC_RADIO_MODEL_UpResNet10":"2D 插图 — UpResNet10 模型",
"IDC_STATIC_CROP_SIZE":"拆分尺寸",
"MessageScaleRateCheckError":"放大倍率必须是大于 0 的正数",
"MessageScaleWidthCheckError":"放大尺寸必须是大于 0 的整数",
"MessageCropSizeCheckError":"拆分大小必须是大于 0 的整数",
"IDC_STATIC_BATCH_SIZE":"批尺寸",
"MessageBatchSizeCheckError":"批尺寸必须是大于 0 的整数"

```

**Comment by yoonhakcher** [comment]
@lltcggie
