### ISSUE TITLE
【GUI版】拡大サイズ指定で、縦幅を指定しても横幅のサイズとして拡大される

### ISSUE THREAD

**Issue by glenxar** [lltcggie/waifu2x-caffe#39]
Ver1.1.5 GUI版 Windows7（64bit）での動作です。
GUI版で画像の拡大サイズ指定において、縦幅のピクセルを指定して拡大しようとすると、指定したピクセルが横幅のピクセルとなってしまいます。

![wife2x_size](https://cloud.githubusercontent.com/assets/20370665/16708302/e2acb32a-4628-11e6-8356-5506b57087c7.PNG)
このように、縦幅に1920ピクセルを指定していますが、実行後に作成されるファイルは縦幅1920ピクセルではなく、横幅1920ピクセルになっていました。

倍率に2.0を指定すると指定通り2倍になりますし、横幅に1920を指定すると、指定通り横幅1920ピクセルの画像が作成されます。
縦幅の指定だけがうまくいっていない様子です。

**Comment by lltcggie** [comment]
報告ありがとうございます。
そのバグはVer 1.1.5リリース後に気づき修正を行いました。 https://github.com/lltcggie/waifu2x-caffe/commit/55149952159d1b18599bff1b4ed0eee1688fbe6d
次バージョンは #38 の修正後リリース予定なので少しお待ち下さい。

**Comment by glenxar** [comment]
早速の返信ありがとうございます。
次期バージョン、楽しみに待ってますね。
