### ISSUE TITLE
ALIENWARE14(2013)でcudaが使えない

### ISSUE THREAD

**Issue by a1678991** [lltcggie/waifu2x-caffe#4]
cuda,cuddnともに選択して実行を押すと「waifu2x-caffe.exeは動作を停止しました」となりGPUが使われてる様子もなくそのまま何も起きません。
他のソフトではcuda使えるのでドライバーがダメとかではないらしい。
Optimus(統合グラフィック+GPU)環境なのでそのせいかもしれないです。

**Comment by lltcggie** [comment]
Optimus環境がないのでなんともいえませんが、特定のソフトを強制的にGPUで動かす方法がない場合はどうしようもないと思います…

**Comment by a1678991** [comment]
NVIDIAコントロールパネルの設定でwaifu2x-caffeとcuiをGPUで動かすようにしていて他のwaifu2x派生ソフトでは同様の設定でGPUを使っているのを確認できたのでその点は問題ないと思います

**Comment by Heiseikiseki** [comment]
こちらもoptimus環境なんです､問題なく動作してます｡
よって､この問題は解決されたと思います｡
