### ISSUE TITLE
Incorrect result with tta mode and different crop_w & crop_h value

### ISSUE THREAD

**Issue by HolyWu** [lltcggie/waifu2x-caffe#43]
Source (640x360)
![foo](https://cloud.githubusercontent.com/assets/5151987/17354955/7d9a66d4-597f-11e6-8996-ba0209f49a3a.png)

`waifu2x-caffe-cui.exe --tta 0 --crop_w 160 --crop_h 180 -p cudnn -m scale -i foo.png`
![foo uprgb scale x2 000000](https://cloud.githubusercontent.com/assets/5151987/17354979/ab2fdcaa-597f-11e6-92b9-660806cefa09.png)

`waifu2x-caffe-cui.exe --tta 1 --crop_w 160 --crop_h 180 -p cudnn -m scale -i foo.png`
![foo uprgb scale tta x2 000000](https://cloud.githubusercontent.com/assets/5151987/17354991/d1173152-597f-11e6-96d5-c24f71f1474b.png)

The problem also doesn't occur when you assign the same value to both crop_w and crop_h.

**Comment by lltcggie** [comment]
修正しました
