### ISSUE TITLE
my caffe have no “SetGetcuDNNAlgorithmFunc ” 

### ISSUE THREAD

**Issue by yuyadanyadan** [lltcggie/waifu2x-caffe#46]

**Comment by yuyadanyadan** [comment]
Hi,
I build  a project with your code in ubuntu14.04 with Nsight Eclipse. Error: my caffe::Caffe don't have SetGetcuDNNAlgorithmFunc and SetSetcuDNNAlgorithmFunc. Are they your own functions?
Hoping for your reply! Thank you !

**Comment by lltcggie** [comment]
こちらのCaffeを使っています。
ただし、Ubuntuではビルドしたことがないのでエラーが出る可能性があります。
https://github.com/lltcggie/caffe

**Comment by nagadomi** [comment]
Yes, waifu2x-caffe is required lltcggie's customized caffe.
I provide lltcggie's caffe and waifu2x-caffe for ubuntu.
Maybe it will helpful for you https://github.com/nagadomi/waifu2x-caffe/blob/ubuntu/INSTALL-linux.md

**Comment by yuyadanyadan** [comment]
I'm grateful! Thank you so much !

在 2016-08-16 17:41:59，"nagadomi" <notifications@github.com> 写道：


Yes, waifu2x-caffe is required lltcggie's customized caffe.
I provide lltcggie's caffe and waifu2x-caffe for ubuntu.
Maybe it will helpful for you https://github.com/nagadomi/waifu2x-caffe/blob/ubuntu/INSTALL-linux.md

**Comment by yuyadanyadan** [comment]
Hi,
I use your caffe to run the waifu2x net . And I get: Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM (#241)

在 2016-08-16 16:44:58，"lltcggie" <notifications@github.com> 写道：


こちらのCaffeを使っています。
ただし、Ubuntuではビルドしたことがないのでエラーが出る可能性があります。
https://github.com/lltcggie/caffe

**Comment by yuyadanyadan** [comment]
This is my net! Could you help me? Thank you so much


name: "upconv_7"
layer {
name: "data"
type: "Data"
top: "input_data"
include {
phase: TRAIN
}
transform_param {
scale: 0.00392156
mirror: true
mean_file: "/home/yuyadan/src/sourceCode/lltcggie-caffe/data/waifu2x_trainning_cpp/waifu2x_mean.binaryproto"
}
data_param {
source: "/home/yuyadan/src/sourceCode/lltcggie-caffe/examples/waifu2x_trainning_cpp/waifu2x_train0_lmdb"
batch_size: 10
backend: LMDB
}
}
layer {
name: "data"
type: "Data"
top: "input_data"
include {
phase: TEST
}
transform_param {
scale: 0.00392156
mirror: true
mean_file: "/home/yuyadan/src/sourceCode/lltcggie-caffe/data/waifu2x_trainning_cpp/waifu2x_mean.binaryproto"
}
data_param {
source: "/home/yuyadan/src/sourceCode/lltcggie-caffe/examples/waifu2x_trainning_cpp/waifu2x_val0_lmdb"
batch_size: 10
backend: LMDB
}
}
layer {
name: "conv1_layer"
type: "Convolution"
bottom: "input_data"
top: "conv1"
convolution_param {
num_output: 16
kernel_size: 3
stride: 1
bias_filler{
type: "constant"
value: 0
}
weight_filler {
type: "gaussian"
std: 0.01
}
}
}
layer {
name: "conv1_relu_layer"
type: "ReLU"
bottom: "conv1"
top: "conv1"
relu_param {
negative_slope: 0.1
}
}
layer {
name: "conv2_layer"
type: "Convolution"
bottom: "conv1"
top: "conv2"
convolution_param {
num_output: 32
kernel_size: 3
stride: 1
bias_term: false
weight_filler {
type: "gaussian"
std: 0.01
}
}
}
layer {
name: "conv2_relu_layer"
type: "ReLU"
bottom: "conv2"
top: "conv2"
relu_param {
negative_slope: 0.1
}
}
layer {
name: "conv3_layer"
type: "Convolution"
bottom: "conv2"
top: "conv3"
convolution_param {
num_output: 64
kernel_size: 3
stride: 1
bias_term: false
weight_filler {
type: "gaussian"
std: 0.01
}
}
}
layer {
name: "conv3_relu_layer"
type: "ReLU"
bottom: "conv3"
top: "conv3"
relu_param {
negative_slope: 0.1
}
}
layer {
name: "conv4_layer"
type: "Convolution"
bottom: "conv3"
top: "conv4"
convolution_param {
num_output: 128
kernel_size: 3
stride: 1
bias_term: false
weight_filler {
type: "gaussian"
std: 0.01
}
}
}
layer {
name: "conv4_relu_layer"
type: "ReLU"
bottom: "conv4"
top: "conv4"
relu_param {
negative_slope: 0.1
}
}
layer {
name: "conv5_layer"
type: "Convolution"
bottom: "conv4"
top: "conv5"
convolution_param {
num_output: 128
kernel_size: 3
stride: 1
bias_term: false
weight_filler {
type: "gaussian"
std: 0.01
}
}
}
layer {
name: "conv5_relu_layer"
type: "ReLU"
bottom: "conv5"
top: "conv5"
relu_param {
negative_slope: 0.1
}
}
layer {
name: "conv6_layer"
type: "Convolution"
bottom: "conv5"
top: "conv6"
convolution_param {
num_output: 256
kernel_size: 3
stride: 1
bias_term: false
weight_filler {
type: "gaussian"
std: 0.01
}
}
}
layer {
name: "conv6_relu_layer"
type: "ReLU"
bottom: "conv6"
top: "conv6"
relu_param {
negative_slope: 0.1
}
}
layer {
name: "conv7_layer"
type: "Deconvolution"
bottom: "conv6"
top: "conv7"
convolution_param {
num_output: 3
kernel_size: 4
stride: 2
pad: 3
bias_term: false
weight_filler {
type: "gaussian"
std: 0.01
}
}
param {
lr_mult: 0
decay_mult: 0
}
}
layer {
name: "target"
type: "Data"
top: "target"
transform_param{
scale: 0.00392156
mirror: true
mean_file: "/home/yuyadan/src/sourceCode/lltcggie-caffe/data/waifu2x_trainning_cpp/waifu2x_mean_out.binaryproto"
}
data_param {
source: "/home/yuyadan/src/sourceCode/lltcggie-caffe/examples/waifu2x_trainning_cpp/waifu2x_train1_lmdb"
batch_size: 10
backend: LMDB
}
include: { phase: TRAIN }
}
layer {
name: "target"
type: "Data"
top: "target"
transform_param{
scale: 0.00392156
mirror: true
mean_file: "/home/yuyadan/src/sourceCode/lltcggie-caffe/data/waifu2x_trainning_cpp/waifu2x_mean_out.binaryproto"
}
data_param {
source: "/home/yuyadan/src/sourceCode/lltcggie-caffe/examples/waifu2x_trainning_cpp/waifu2x_val1_lmdb"
batch_size: 10
backend: LMDB
}
include: { phase: TEST }
}
layer {
name: "loss"
type: "EuclideanLoss"
bottom: "conv7"
bottom: "target"
top: "loss"
#include: { phase: TRAIN }
}

在 2016-08-16 16:44:58，"lltcggie" <notifications@github.com> 写道：


こちらのCaffeを使っています。
ただし、Ubuntuではビルドしたことがないのでエラーが出る可能性があります。
https://github.com/lltcggie/caffe
