### ISSUE TITLE
Binary DLL distribution

### ISSUE THREAD

**Issue by Bargest** [lltcggie/waifu2x-caffe#48]
Current distribution contains GUI and console versions. But there is a DLL project in sources.
I have only VS 2015, which means I can't build caffe and waifu2x-caffe without installing the older 2013 one.
Could you please add DLL-version in your binary distribution?

**Comment by lltcggie** [comment]
DLLのプロジェクトは公開するつもりがなかったけどコミットしてしまったので置いたままにしてあるだけです。
DLLの方まではサポートする余裕がありません。
自分でビルドしてください。
https://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx

**Comment by Bargest** [comment]
Well, I went through hell but finally managed to build caffe and your project with VS2015 + Cuda 8.0 + boost 1.6. :)

Thanks for you project anyway. It helps me very much now.
