### ISSUE TITLE
X86 OS support requested

### ISSUE THREAD

**Issue by LShining** [lltcggie/waifu2x-caffe#49]
Current version can only be run on X64 Windows OS, can we add support for X86(32-bit) systems?

**Comment by lltcggie** [comment]
以下の理由により対応する予定はありません。

- x86用に各種ライブラリをビルドがするのが大変(そもそもCaffeはx86用にビルドできるかどうかもわからない)
- ビルドできたとしても正常に動くのかわからないので動作確認が大変
- cuDNNを使って変換するのを想定しているが、cuDNNがx64版しかない
