### ISSUE TITLE
Latest version 1.0.8 ALWAYS crashes, Cannot use

### ISSUE THREAD

**Issue by Airbus480** [lltcggie/waifu2x-caffe#5]
The latest version 1.0.8 always crash (application crash) whenever I press the "run" button no matter parameters I set, the previous version (1.0.7) does not crash
in japanese:その最新ヴァージョン（1.0.8）は、どんなパラメーターに設定しようが run ボタンを押すと必ずクラッシュ（異常終了）してしまいます。以前のヴァージョン（1.0.7）はクラッシュしません。
![latest](https://cloud.githubusercontent.com/assets/16185735/11621220/e7a660a2-9cf4-11e5-976c-8086fddac799.png)
OS:Win 7 pro 64 bit
btw does waifu2x-caffe support SLI?

**Comment by lltcggie** [comment]
GPUの種類によってはクラッシュするバグをver 1.0.8.1で修正しましたが、ver 1.0.8.1でも動かないでしょうか？

**Comment by Airbus480** [comment]
It does not crash anymore using version 1.0.8.1
However upscaling 900x1200 image to 8000x10800 with TTA waifu2x-caffe crashes.
