### ISSUE TITLE
BMP file outputs come out with a modified alpha channel

### ISSUE THREAD

**Issue by FlatCell** [lltcggie/waifu2x-caffe#50]
So i tried do Magnify a bunch of .bmp files but the output comes out with a messed up alpha channel.
![example](https://cloud.githubusercontent.com/assets/9400167/18333906/09299bbe-756b-11e6-92c4-a24e6fece10a.png)
![settings](https://cloud.githubusercontent.com/assets/9400167/18333913/138046b2-756b-11e6-80b3-14403aa5e3b2.png)
Just wanted to say thanks in advance and keep up the good work!

**Comment by lltcggie** [comment]
再現しないので、Input.bmpをアップロードしていただけないでしょうか？
よろしくお願いします。

**Comment by FlatCell** [comment]
Sure here is the link to the file:
https://drive.google.com/file/d/0Bweq4bg_RcmCNTVoS0stVEl0VGM/view?usp=sharing

**Comment by nagadomi** [comment]
ImageMagick/GraphicsMagick has the same problem.
But it seems that this is browser/viewer side bug. the result of waifu2x-caffe is correct.

R channel:
![r](https://cloud.githubusercontent.com/assets/287255/18417277/ecf19f3e-7865-11e6-9462-4fc8611a73c4.png)

G channel:
![g](https://cloud.githubusercontent.com/assets/287255/18417279/f24d9136-7865-11e6-81cc-dbd93a2abf7e.png)

B channel:
![b](https://cloud.githubusercontent.com/assets/287255/18417281/f6d9924a-7865-11e6-894c-e04ed20ef356.png)

A channel:
![a](https://cloud.githubusercontent.com/assets/287255/18417283/fb292d9c-7865-11e6-8300-2f7ee9570413.png)

R+G+B:
![rgb](https://cloud.githubusercontent.com/assets/287255/18417284/06faae52-7866-11e6-85c6-9687147ef78a.png)

R+G+B+A:
![rgba](https://cloud.githubusercontent.com/assets/287255/18417286/0e7f7c66-7866-11e6-9bef-0af2625d88ea.png)

**Comment by nagadomi** [comment]
> BMP3 does not allow transparency
> http://www.imagemagick.org/discourse-server/viewtopic.php?t=28733#p127820

Maybe browser/viewer follows the above specification.

**Comment by FlatCell** [comment]
I use gimp and gimp doesn't even detect an Alpha channel in any of those but I installed Photoshop just too check and yeah the output is indeed correct, just the preview has changed. But I found another weird thing. This is the input, notice that "smudge" of color around the character.
![input](https://cloud.githubusercontent.com/assets/9400167/18418487/5a04ac28-783f-11e6-88c1-9bfe5caafcc3.png)
![output 2](https://cloud.githubusercontent.com/assets/9400167/18418507/9cc4640e-783f-11e6-8c1c-eca4e529fdf1.png)

This is the Output, this is the reason why I thought it was a problem with Alpha channel. But after opening the images above in Photoshop the alpha channel is indeed correct but the color channel's aren't.

**Comment by lltcggie** [comment]
@nagadomi さんが書いてくださったとおり、このソフト自体は意図した動作をしています。
また、完全に透明なピクセル(アルファ値が0)のある画像を変換すると、周りにノイズのようなものが乗るのは仕様です。
処理の都合上、不透明な箇所と透明な箇所の境界を引き延ばす必要があります。
さらに、処理の最初でRGBとAを掛けることにより、完全に透明なピクセルの値を0にしています。
なので、変換を行うとアルファ値が0のピクセルの内容は失われます。

**Comment by nagadomi** [comment]
waifu2x-caffe and waifu2x(http://waifu2x.udp.jp) will break the RGB pixels in 100% transparent area. The behavior is by current design.

**Comment by FlatCell** [comment]
Ok thanks for all the info, I'll close the issue since it's not really an issue at all. Keep up the good work!
