### ISSUE TITLE
【機能要望】アルファチャンネルを破棄するオプション

### ISSUE THREAD

**Issue by kztrymgt** [lltcggie/waifu2x-caffe#51]
意図せずアルファチャンネルが残っている画像を処理するときの速度を向上したいと思っております。
そこで、対象画像のアルファチャンネルを破棄して処理するオプションを実装していただけないでしょうか。（主にCUI版）
不躾なお願いで恐縮ですが、何卒ご検討ください。

**Comment by lltcggie** [comment]
ver 1.1.8でアルファチャンネルが単色（つまり同一色で塗りつぶされている）の場合、アルファチャンネルの拡大にニアレストネイバー法を使用するようにしました。
これで意図せずにアルファチャンネルが残っている画像の大部分はアルファチャンネルなしの画像とほぼ同じ速度で処理できるようになったはずです。
一部半透明、あるいは透明な部分がある画像は、他の方法でアルファチャンネルを除去してからこのソフトで拡大するようにしてください。

**Comment by kztrymgt** [comment]
アルファチャンネルが単色のものについてはかなり高速化され、ImageMagickでアルファチャンネル削除→waifu2x-caffe-cuiで変換するよりも短時間で処理できるようになりました。
対応ありがとうございました。
