### ISSUE TITLE
System frozen with ver 1.1.7.1

### ISSUE THREAD

**Issue by Explorare** [lltcggie/waifu2x-caffe#52]
I found my waifu2x-caffe can't use cudnn any more. It will cause system frozen and have to be shut down  forcibly. I've tried different combinations to locate the problem.

Case 1:
waifu2x-caffe v1.1.7.1 + cudnn-8.0 v5.1 + GeForce 372.70 / 368.81
System frozen.

Case 2:
waifu2x-caffe v1.1.7.1 + cudnn-8.0 v5.1 + GeForce 364.96
Error: Input can not be converted by GPU. The CUDA driver may not have been installed. Please install the CUDA driver.

Case 3:
waifu2x-caffe v1.1.3.2 + cudnn-7.0 v4.0 + GeForce 364.96
You can not use cuDNN. cFailed to intialize cuDNN.

So what can I do to fix this?

**Comment by YukiSakuma** [comment]
I am using 1.1.7.1, 372.54 and cudnn 8.0 v5.1 but I doubt it's the nvidia drivers how do you reproduce the problem?

**Comment by Explorare** [comment]
I roll back my system to 2016-09-02, and it works again like before. The driver now I'm using is 372.70. So I think something else effect the cudnn driver.

**Comment by lltcggie** [comment]
waifu2x-caffe ver 1.1.8 + cudnn-8.0 v5.1(RCではなく) + 最新版のGeForceドライバ
だとどうなりますか？

**Comment by Explorare** [comment]
waifu2x-caffe ver 1.1.8 + cudnn-8.0 v5.1 + NVIDIA 373.06 works fine on Windows 8.1 Enterprise x64. Thanks.
