### ISSUE TITLE
CUDA can not use

### ISSUE THREAD

**Issue by teruspot** [lltcggie/waifu2x-caffe#58]
Once I use video card processing，the card will be remove ,system not detecte the video card,the error like  [this](http://i.imgur.com/LMsfESN.png)
gtx950m,driver verson  [372.90](http://i.imgur.com/VSlRTxZ.png)

**Comment by lltcggie** [comment]
OptimusでIntelの内蔵GPUを使う設定になっている可能性があります。
このソフトをGTX 950Mを使うように設定してください。
