### ISSUE TITLE
【機能要望】文字だけの画像を特化するモデルが欲しい

### ISSUE THREAD

**Issue by zambast** [lltcggie/waifu2x-caffe#59]
例えば小説とかのスキャン画像をアップスケールする時、今のモデルより画質いい変換可能のモデルは存在するでしょうか。もし存在するなら、追加してほしいです。

**Comment by lltcggie** [comment]
文字だけの画像に特化したモデルはありません。
waifu2xを使って自分で学習させてみてください。
https://github.com/nagadomi/waifu2x
