### ISSUE TITLE
[リクエスト]WebPの入力対応､cudnnv4､2x modelの更新など

### ISSUE THREAD

**Issue by Heiseikiseki** [lltcggie/waifu2x-caffe#6]
issueではありませんが､WebPフォマットの入力対応をお願いします｡
https://developers.google.com/speed/webp/docs/api

ちなみにcudnnv4も出ました

また､本家の2x model､ default parameterも12月11日に更新されました｡

次のバージョンのwaifu2x-caffeを気を長くしてお待ちしております｡

**Comment by lltcggie** [comment]
WebPとモデルの拡大に対応しました。
cuDNN v4 RCはまだリリースしていませんが既に対応を完了しています。
本家のdefault parameterの変更は学習にのみ関係するパラメータの変更なので影響はありません。

実行ファイルの更新はリリースするので少々お待ち下さい

**Comment by Heiseikiseki** [comment]
いつもいつもありがとうございます!!!心から感謝しています!!!
