### ISSUE TITLE
Cannot find 「cudnn64_5.dll」

### ISSUE THREAD

**Issue by ikacarrot** [lltcggie/waifu2x-caffe#62]
Questions are as follows:
Under  「waifu2x-caffe ver 1.1.7.1」,
Calling cuDNN failed, cannot find 「cudnn64_5.dll」 
System:
Windows 7 x64
Graphics Card:
NVIDIA GTX 970
Driver Version:
369.30

I have installed 「CUDA Version 8.0.44」, how to solve, very grateful !

**Comment by YukiSakuma** [comment]
CUDNN is free but you have to register and download at this site:
https://developer.nvidia.com/cudnn

**Comment by ikacarrot** [comment]
My question has been resolved, many thanks !
