### ISSUE TITLE
CUDA toolkit 8.0 update reuqest.

### ISSUE THREAD

**Issue by fuchanghao** [lltcggie/waifu2x-caffe#63]
https://developer.nvidia.com/cuda-toolkit

CUDA toolkit 8.0 released.

the vapoursynth tools of waifu2x-caffe already support 8.0.

https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe

will you update it sometime?

**Comment by lltcggie** [comment]
ver 1.1.8で更新しました。
