### ISSUE TITLE
Input can not be converted by GPU (version 1.1.8)

### ISSUE THREAD

**Issue by YukiSakuma** [lltcggie/waifu2x-caffe#65]
1.1.8
![1 1 8](https://cloud.githubusercontent.com/assets/16185735/20024439/8bb97ade-a321-11e6-98a2-438b40a304bd.JPG)
Current Nvidia driver version 368.69
Is there a way to update to CUDA 8.0 while maintaining 368.69?

**Comment by lltcggie** [comment]
CUDA 8.0に対応した最新のドライバーに更新してください
