### ISSUE TITLE
about library..

### ISSUE THREAD

**Issue by always-awaken** [lltcggie/waifu2x-caffe#68]
no such file proto.lib 
#pragma comment(lib, "proto.lib") <-- error

#pragma comment(lib, "libprotobuf.lib")
There is already a protobuf library on this line.

what is proto.lib?

**Comment by nagadomi** [comment]
It's a module of caffe. You should build caffe libs first. https://github.com/lltcggie/caffe-builder

**Comment by always-awaken** [comment]
Thank you for your help.
I succeeded Caffe libs but I still have errors
`LNK2001: mdb_env_close unresolved external symbol.	C:\waifu2x-caffe-master\waifu2x-caffe-dll\caffe.lib(db_lmdb.obj)	waifu2x-caffe-dll`

i guess `caffe.lib` doesn't open the `lmdb.lib`

Caffe builder option is like this

![image](https://cloud.githubusercontent.com/assets/15225038/21175303/ed42ee08-c224-11e6-8490-472f94f31666.png)

**Comment by always-awaken** [comment]
Solved them!

unchecked USER_LMDB and USER_LEVELDB

**Comment by nagadomi** [comment]
yeah, lltcggie presented the cmake option at https://gist.github.com/lltcggie/6af687bca94aba8c78b4
