### ISSUE TITLE
space used on operating disk

### ISSUE THREAD

**Issue by mystro1213** [lltcggie/waifu2x-caffe#69]
did some upscale and my c is 200mb the output folder is 1.2gb
my c drive was 20gb 
you really need to fix this as it takes space and the extra files or the things that took the space can't be found

**Comment by YukiSakuma** [comment]
I am trying to understand your sentence here
Your current C drive is now 200MiB free space and before it was 20GiB?
The output folder which you waifued is a total size of 1.2GiB?
I can only suspect that the paging file is causing it. 
Try testing it on another hard disk other than your C drive and find "the extra files" that's causing the used space
