### ISSUE TITLE
Unnecessary artifact/color using ver 1.1.0

### ISSUE THREAD

**Issue by Airbus480** [lltcggie/waifu2x-caffe#7]
Hello it's me again. I tried using the latest version and compare it to version 1.0.8.1 
Test image:
![miku_bg](https://cloud.githubusercontent.com/assets/16185735/12008542/09019cd4-ac7d-11e5-818d-98d769465384.png)
Now the problem is:
![forupload](https://cloud.githubusercontent.com/assets/16185735/12008541/e800a368-ac7c-11e5-8a2a-41ee9af0978f.png)
All parameters used: 5x scale,RGB, TTA, level 1 denoise, output: PNG 
Other Model parameters ver 1.1.0
Photo model:
![miku_bg photo noise_scale level1 tta x5 000000](https://cloud.githubusercontent.com/assets/16185735/12008560/b7158208-ac7e-11e5-8608-fe64b04bca83.png)
Y-model:
![miku_bg y noise_scale level1 tta x5 000000](https://cloud.githubusercontent.com/assets/16185735/12008561/c1dc950a-ac7e-11e5-8f8d-ea9ed1059c5b.png)

**Comment by lltcggie** [comment]
ver 1.1.1で修正できたと思うのですが、どうでしょうか？

RGB model
![org rgb noise_scale level1 tta x5 000000](https://cloud.githubusercontent.com/assets/7032792/12009945/223dead0-acd3-11e5-98c2-f5c31bb2b9ad.png)

Photo model
![org photo noise_scale level1 tta x5 000000](https://cloud.githubusercontent.com/assets/7032792/12009949/3108802a-acd3-11e5-9c82-1a1d1bc8f9bd.png)

**Comment by Heiseikiseki** [comment]
The author has fixed the problem and release the new version 1.1.1.

**Comment by Airbus480** [comment]
Okay it's fixed thanks!
