### ISSUE TITLE
About Cropping Image

### ISSUE THREAD

**Issue by always-awaken** [lltcggie/waifu2x-caffe#72]
I know increase upscaling speed if I increase crop size.  but i have still questions.

If you cut the image, there would be a midpoint between the merging

how can you cropping Image outline upscale it?

**Comment by lltcggie** [comment]
出力の1ピクセルに対して影響する入力の範囲が分割したときとしないときとで同じになるように、分割した画像のの境界の一定範囲をオーバーラップして分割するようにしています。
なので分割サイズを変更したとき、あるいは分割しなかったときの出力はすべて同じものになるはずです。
