### ISSUE TITLE
Use this with an old Nvidia GPU? 

### ISSUE THREAD

**Issue by GiRaFa-SM** [lltcggie/waifu2x-caffe#73]
My R9 280 just died and I have some Nvidias Quadro FX 580  here, I can use them to process some images? 
I've tried to use them in the past but the program returned me the message :no Cuda device found. What am I doing wrong? 
I know that my video card has 1.1 compute capability.

**Comment by lltcggie** [comment]
[README.md](https://github.com/lltcggie/waifu2x-caffe/blob/master/README.md) の要求環境を読んでください。
