### ISSUE TITLE
Why does waifu2x use so much system memory?

### ISSUE THREAD

**Issue by RikuKawai** [lltcggie/waifu2x-caffe#74]
Is there any way to utilize as much VRAM as possible and minimize RAM usage?

I have 8GB of VRAM but it's only using 1GB of my VRAM and 4GB of my system RAM.

Using a GTX 1070 (Notebook, 2048 CUDA cores) with 8GB GDDR5, i5-7600K @4.8GHz, 16GB DDR4-2400, Windows 10 Pro x64, waifu2x-caffe v1.1.8.

**Comment by lltcggie** [comment]
最終的な出力画像のサイズが大きくなると、RAMで確保するバッファのサイズが大きくなります。
