### ISSUE TITLE
waifu2x running on a paid server with gpu?

### ISSUE THREAD

**Issue by annasophiachristianahahn** [lltcggie/waifu2x-caffe#76]
Hello

I am currently using waifu2x caffe in windows on a laptop with no gpu. Since it is running only on a dual core 2.7 ghz cpu the 288% resize is going quite slow and I have multiple images I would like to process. Is anyone aware of an implementation of waifu2x that runs on a remote server that DOES NOT have size limitations? I plan on bumping up multiple images from 5000x5000px to 14000x14000px and would be willing to use a paid service/rent server time if there were an easy way to do so. 

Any suggestions infinitely appreciated thanks so much!

**Comment by lltcggie** [comment]
リモートサーバーにwaifu2x環境を構築したいのであれば、知識が必要ですが[本家の説明にあるPublic AMI](https://github.com/nagadomi/waifu2x)が一番簡単な構築方法だと思います。（実際に触ったことはありませんが）

**Comment by annasophiachristianahahn** [comment]
Thanks so much for the quick reply. I am not very good with coding and thus don't think I could set this up very well myself however I would be willing to pay for access/time on someone else's implementation- are you aware of anyone setting up an implementation without size limitations on a remote server that might be willing to sell me access?

**Comment by lltcggie** [comment]
サイズ制限なしでwaifu2xを使って画像を拡大するサービスは、僕も聞いたことがありません（有料でも）。
