### ISSUE TITLE
アルファチャンネル付きPNG画像の変換時アルファチャンネルが消失することがある

### ISSUE THREAD

**Issue by Hand-culveriN** [lltcggie/waifu2x-caffe#8]
Ver.1.1.1にて
「ノイズ除去」 「ノイズ除去(自動判別)と拡大」のいずれかを選択して変換した場合にアルファチャンネルが消失するようです

**Comment by lltcggie** [comment]
ver 1.1.1.1で修正できたと思うのですが、いかがでしょうか？

**Comment by Hand-culveriN** [comment]
Ver 1.1.1.1で修正されていることを確認しました
対応ありがとうございました
