### ISSUE TITLE
Crushed when selecting output folder

### ISSUE THREAD

**Issue by Skimige** [lltcggie/waifu2x-caffe#82]
OS Windows 10 Pro x64 1607
Steps:
1. drop a png file to the inputbox
2. select the output folder, choose desktop, and click the white background of the selection window
3. waifu2x-caffe have stopped working.

Screenshot:
![preview](http://i.imgur.com/qD3u1oo.png)

**Comment by YukiSakuma** [comment]
I can confirm it also happens on Windows 7 Pro x64. It just closes on its own.

**Comment by lltcggie** [comment]
修正しました
