### ISSUE TITLE
Output image width is slightly different with width parameter

### ISSUE THREAD

**Issue by starrin** [lltcggie/waifu2x-caffe#84]
![323957](https://cloud.githubusercontent.com/assets/2861959/25538595/f04009fe-2c75-11e7-925c-1bfd46481603.jpg)

Process this image with width parameter 2000px, the output image width would be 1999px.
Happens with input image width at 870px and width parameter between 1000px to 2000px.

**Comment by lltcggie** [comment]
修正しました
