### ISSUE TITLE
Caffe succeeded by Caffe2

### ISSUE THREAD

**Issue by Hikari-chin** [lltcggie/waifu2x-caffe#85]
Not a major issue, more like a feature request, but I figured I should mention that Caffe has been deprecated in favor of Caffe2:

https://developer.nvidia.com/caffe2

Are there any plans to switch waifu2x-caffe to use caffe2? It is supposedly faster and more efficient.

**Comment by lltcggie** [comment]
今のところコストをかけてまで移行する予定はないです。
なぜならwaifu2xでcuDNNを使う場合、Caffeの内部ではCaffe2と同じようにほぼcuDNNを使って畳み込みと逆畳み込みを行っているだけなはずなので、処理速度が向上することはほとんどないと思っているからです。
もし本当に処理速度が向上するのであれば移行を検討します。

**Comment by Hikari-chin** [comment]
了解。ありがとうございます。
