### ISSUE TITLE
Suggestion: Make CUI Unicode-aware

### ISSUE THREAD

**Issue by alemonmk** [lltcggie/waifu2x-caffe#87]
What I want is very similar to what #67 requests.
Current behavior is very unfriendly for building automation tools with it.
The output field of GUI can be overridden to act like -o of CUI, why not -o of GUI?
I can just use the CUI to achieve this, but it is not Unicode-aware, it does not correctly process anything not named in system locale.

I know not much in C++ but I tried to make the CUI Unicode-aware,  just
  - a `_setmode(_fileno(stdout), _O_U16TEXT);`,
  - `string` to `wstring`,
  - `"string"` to `L"string"`,
  - `printf()` to `wprintf()`,
  - also some copy & paste from `waifu2x-caffe-gui/MainDialog.cpp`,

but:
  - I've spent ~15 hours on getting cmake to build caffe on VS 2017
    * I tried your [caffe-builder](https://github.com/lltcggie/caffe-builder), but the `Boost.Build` hates VS 2017 toolset and wasted me ~10 hours,
      - Redownloads and unzipping Boost really contribute, even on SSD it's still HELL **SLOOOOOOOW**.
    * Also tried the windows branch of [BVLC/caffe](https://github.com/BVLC/caffe/tree/windows) and the Original caffe-builder but since #46 that's my 6 hours gone.
  - VS 2015 installer says "no" to my machine by crashing itself every time I launch it,
  - The VS 2015 toolset installed with VS 2017 installer is so broken that its own developer command prompt refuse to be useful.
    * But it can be used in VS 2017, what the hell.

This is very frustrating and I don't bother trying again.
I may:
  - on your request create a pull request with my modified `waifu2x-caffe/Source.cpp` and leave the testing to you, or
  - get a working caffe environment from you so I can test it myself before creating PR, or
  - just wait for you to adjust the behavior of -o.

I'm away from coding the next few days so take your time.

**Comment by alemonmk** [comment]
Anyways, here is the commit.
https://github.com/alemonmk/waifu2x-caffe/commit/a54d1ed006f8b2978d11af5fa6ae1daf4ced90db

GitHub treat it as binary so there's no diff ... SmartGit has no problem though.

**Comment by lltcggie** [comment]
CUIでUNICODEでのビルドにも対応しました。 aaa43282701cf41067e3d1020cca35aa2ba88d0b

**Comment by alemonmk** [comment]
Thank you for saving me much headache. :)
