### ISSUE TITLE
Linux support?!?

### ISSUE THREAD

**Issue by julianacat** [lltcggie/waifu2x-caffe#95]
Is there a way to compile this to run natively on linux, running on wine crashes and using a virtual machine is too inconvenient and slow.

**Comment by nagadomi** [comment]
I published a linux port at https://github.com/nagadomi/waifu2x-caffe-ubuntu
but it does not support GUI.

**Comment by julianacat** [comment]
Ive been trying to compile on arch for a while now, Its a hard task but im going to keep at it. Ill close this and ask for help if needed over on your fork. Thanks for the port! @nagadomi

**Comment by nagadomi** [comment]
google "install caffe" might help.
Note that waifu2x-caffe requires the modified version of caffe by lltcggie (https://github.com/lltcggie/caffe). I also provide ubuntu port of that (https://github.com/nagadomi/caffe).

**Comment by viktor02** [comment]
> Ive been trying to compile on arch for a while now, Its a hard task but im going to keep at it. Ill close this and ask for help if needed over on your fork. 

If you managed to do this, I will be grateful if you make an instruction or a package in aur
